### ISSUE TITLE
Doesnt pick prompts with intros on it

### ISSUE THREAD

**Issue by konqiDAM** [RupertAvery/DiffusionToolkit#1]
I had a saved prompt like this one
![image](https://user-images.githubusercontent.com/44301655/205334435-6f3a1d49-0917-4516-8817-1975d76a7fda.png)
Probably I just copy pasted, but on your toolkit it appears like this:
![image](https://user-images.githubusercontent.com/44301655/205334514-50ab5882-7e30-4d1e-97d2-629b7c6c04de.png)

So it seems extra intros are problematic.
Also good job, already reported a bug on reddit, but probably more appropriate here. Great job!

**Comment by RupertAvery** [comment]
Ah, yes, I hadn't thought of this. Thanks for bringing it up.
