### ISSUE TITLE
drag and drop an image only works from the thumbnail pane, not from the large image pane

### ISSUE THREAD

**Issue by laurentopia** [RupertAvery/DiffusionToolkit#100]
A small inconsistency but I found myself drag and dropping to a document from the big image, because that's what I was reacting to,

**Comment by RupertAvery** [comment]
Thanks for your suggestion. I'm wondering how it should work, considering zooming and panning is allowed in the preview.

Should this only activate when the image is not zoomed in?

**Comment by laurentopia** [comment]
RMB for panning and scrollwheel for zooming.

**Comment by RupertAvery** [comment]
Hmm, I dont' think that's intuitive. I'll go with allowing drag-move/copy when zoomed out.

**Comment by laurentopia** [comment]
Middle drag for pan exists in Photoshop, so it's acceptable.
Conditional behavior is the worst type of interaction because it forces context memory.
