### ISSUE TITLE
[BUG] Moving an image to a subfolder of a watched folder doesn't remove it from the database

### ISSUE THREAD

**Issue by Trevor-Z** [RupertAvery/DiffusionToolkit#101]
Using the "move" menu option to move an image to a subfolder of a watched folder doesn't remove it from the database, even if the "Recursive" option is turned off.

Moving it to an unrelated folder works as expected.

**Comment by RupertAvery** [comment]
Found the bug and a fix will be in the next release. 

Thank you!
