### ISSUE TITLE
Allow holding shift to move images to a file explorer folder with drag and drop

### ISSUE THREAD

**Issue by Trevor-Z** [RupertAvery/DiffusionToolkit#102]
We can copy images from DT to other folders in file explorer with drag and drop, it would be useful to be also able to move the files by holding shift.

**Comment by RupertAvery** [comment]
I'm adding this, however, it will match the behavior of Explorer, drag-move is the default (no keys pressed), while holding Ctrl will change it to drag-copy.

**Comment by RupertAvery** [comment]
Fixed in #100
