### ISSUE TITLE
[BUG] Error trying to apply filter to album

### ISSUE THREAD

**Issue by Trevor-Z** [RupertAvery/DiffusionToolkit#103]
Anytime I try to apply a filter to an album, I get this error: 

![Screenshot 2023-04-29 155615](https://user-images.githubusercontent.com/13950948/235319934-a1e6fdf9-db55-43a5-8268-73f7f7ed8c67.png)

**Comment by RupertAvery** [comment]
Thank you forthe bug report, I'll have a fix in the next release
