### ISSUE TITLE
[BUG] The "No Metadata" filter misses many images containing prompts.

### ISSUE THREAD

**Issue by Trevor-Z** [RupertAvery/DiffusionToolkit#105]
This one, for example, is filtered out if I check "No Metadata" and choose "false":

https://civitai.com/images/469235?modelVersionId=42770&prioritizedUserIds=835066&period=AllTime&sort=Most+Reactions&limit=20

How does the detection algorithm work?

By the way, the app is great, and getting even better. I really appreciate your responsiveness on bugs.

**Comment by RupertAvery** [comment]
The Metadata.cs ReadFromFile method contains the code for reading in metadata.  Basically I start by checking the file extension, attempting to find a matching pattern that identifies the metadata as belonging to one of the known AI generators.  Some people store the metadata separately in a .txt file so I check for that as well (afaik StableDiffusion and A1111 allows this).

If no AI-related EXIF/PNG tags/TXT were found, then I assume that it has no metadata, and that is the fallback mechanism.

I downloaded the image, it seems to work for me:

Set No metadata: false (I want to find images that HAVE metadata)

![image](https://user-images.githubusercontent.com/1910659/235383425-94f3757d-6c5e-406f-b210-c3fd6dd8acfc.png)

Appears in the results:

![image](https://user-images.githubusercontent.com/1910659/235383439-140f05db-ddde-4f86-a3b6-b1ca4c2394b1.png)

**Comment by Trevor-Z** [comment]
Yes, that's how I was using it, "No Metadata" and "false" to show only images with metadata.

Now I turned filtering off, and the same image appeared twice in the thumbnails. So I closed the app, deleted the database, opened it again, updated to the latest version, and it seems to be working as expected now.

I don't know what the issue was.

**Comment by Trevor-Z** [comment]
I found out why other images weren't showing up. It's not the filter, it's because some images on Civitai are png's renamed to jpeg, and DT doesn't recognize them until I fix the extensions.

**Comment by RupertAvery** [comment]
Great, I'll add .jpeg to the default file extensions.  I'll close this issue.
