### ISSUE TITLE
Any plans to support Linux

### ISSUE THREAD

**Issue by RandomLegend** [RupertAvery/DiffusionToolkit#11]
Haven't tested if this works via Wine but will try later.

Nay plans to support it officially though?

**Comment by RupertAvery** [comment]
Unfortunately WPF is strictly windows, and I have no plans to try to get this to work cross platform with other frameworks, as it would be a huge rewrite.

**Comment by RandomLegend** [comment]
I understand that it would be a huge undertaking. Just consider that Stable Diffusion is very popular on Linux and you would have a fantastic tool for us here.

I tried to run it via Wine (a translation layer to run windows applications under linux). Problem is, that .NET 6.0 is not really usable under wine at the moment. Atleast not like you would on Windows. We have .NET 6.0 and can install it, but wine apparently cannot access it.

I read some forumposts where it said that if an application ships its own integrated version of .NET 6.0 inside the .exe file, then wine should be okay with running it.

Is that something you could consider? If this isn't that much of a rewrite this could potentially give us Linux users access to your program.

**Comment by RupertAvery** [comment]
As far as I know, WPF (the UI framework I am using), is not supported in Linux.  It is highly windows-centric (built around DirectX I believe) and there have been no plans to port it natively. 

I have had experience building .NET 6 applications for linux, but they were console only. In this regard, building standalone .NET 6 applications for linux work very well.

Unfortunately, even the latest UI framework (MAUI) is not supported in Linux, and there would proabably be a lot to rewrite, not a direct port between WPF and MAUI, although they both might use XAML.

A friend of mine took interest in my application (and it's lack of cross-platform support) and has tried making a Flutter app. It's VERY basic, and just loads thumbnails and the preview with prompt info, but maybe that can be an avenue I can exploer towards the future.

There is also the possibility I can write the application in C++/Qt as I have has some limited experience with that.

However I have invested quite some time in this application and I have a lot of features I'd still like to add.

**Comment by RupertAvery** [comment]
Have you tried this?

https://ccifra.github.io/PortingWPFAppsToLinux/Overview.html

I don't expect it to work out of the box, and there might be some issues, but maybe it could provide some logs or errors so try to get it kind of working.

**Comment by RandomLegend** [comment]
Yeah, this is a bit over my head i assume - i already found a alternative that works on Linux though.

Wish you a merry christmas and a happy new year!

**Comment by unai-ndz** [comment]
At least it works, will check it out soon.
