### ISSUE TITLE
[BUG] Albums not working properly / easilty break

### ISSUE THREAD

**Issue by mvanzorn** [RupertAvery/DiffusionToolkit#110]
Thanks for your work on this project!

**Describe the bug**
Albums have bugs. Adding from filtered results, or adding items in a second pass to an existing album breaks the album.

**Version:**
1.2.1

**To Reproduce**
Reproduction 1: Filter whole collection of images by a positive prompt keyword. Something simple, or something more complex like a lora tag. Then select the resulting thumbnails, right click, and select create new album. Sometimes this works, sometimes it doesn't. When it doesn't work, the album is the entire collection. 

Reproduction 2: Manually create an album. Then drag and drop a few thumbnails from unfiltered collection into that album, then go back to viewing the whole collection, filter by prompt, then try to add the results to the album (result: Album is now the entire collection)

Once the albums stop working properly, two things are consistent:
1. The results line below thumbnails starts reporting negative size numbers, like:
18,730 results found (-69,584,200 B)
2. Any attempts to create new albums fail, always creating an album of the entire collection

**Expected behavior**
The Album appears on the left. Clicking the album title shows the filtered list as above. No weird results found metrics showing beneat the thumbnails area. Adding thumbnails to an album doesn't break it.

Thanks for any suggestions

**Comment by mvanzorn** [comment]
Quitting and restarting the app temporarily restores the albums to working order. But then after filtering and paging through results and adding images to an album, they break again.

**Comment by RupertAvery** [comment]
Thanks, for reporting this issue, I'll look into it

**Comment by RupertAvery** [comment]
Can you check if this version fixes the filtering issue?

[v1.2.2.zip](https://github.com/RupertAvery/DiffusionToolkit/files/12193138/v1.2.2.zip)

**Comment by Correiae** [comment]
Yes !

**Comment by RupertAvery** [comment]
Will be included in next realease
