### ISSUE TITLE
[BUG] when scrollwheeling the image selector resets to first image

### ISSUE THREAD

**Issue by laurentopia** [RupertAvery/DiffusionToolkit#111]
1. use WASD to scrub through the images
2. use scrollwheel to scoll in the image directory pane
= next image WASDed is the first image at the top of the directory pane
expected: next image WASDed is the next image

**Comment by RupertAvery** [comment]
I can't seem to replicate this behavior.

If I WASD, then scroll, then WASD again, it picks up where I left it. It does not reset to the first image.

Tried in 1.2.1

**Comment by laurentopia** [comment]
1.2.2 no longer exhibits this behavior
