### ISSUE TITLE
[BUG] The show info key does not work when the preview has focus.

### ISSUE THREAD

**Issue by acorderob** [RupertAvery/DiffusionToolkit#119]
**Describe the bug**
Other keys work, the problem seems to be only with that one.

**Version:**
1.2.1

**To Reproduce**
Click on the preview panel, press "I", nothing happens.

**Expected behavior**
It should show or hide the info panel.

**Comment by RupertAvery** [comment]
Thanks for reporting, the fix will be in the next release
