### ISSUE TITLE
Sort album list and see what albums images are a member of

### ISSUE THREAD

**Issue by jonk999** [RupertAvery/DiffusionToolkit#126]
Currently there is no way to order Albums in the display pane. I think it would be a good feature to be able to sort them. Even if just alphabetically in ascending/descending order. It would make adding images to albums that aren't in the top 10 easier when listed alphabetically.

Also, it would be handy to know which albums images are a member of. Perhaps in the show info window when viewing an image.

**Comment by RupertAvery** [comment]
Thanks, I'll see what I can do for sorting.  I'm currently trying a drag and drop implementation.  I'll also probably add album filtering by a search box.

**Comment by mattehicks** [comment]
I want to piggyback on this issue and ask if there is a way to export a list of files from an album?  I'd like to be able to sort my images, and find them in the Windows explorer as members of an Album.   Filtered either by metadata or by physically moving them to a named folder.  Is this possible, or any workaround currently?

**Comment by RupertAvery** [comment]
I'm planning to add a feature to do a bunch of stuff to albums, such as export parameters to a single text file to input into A1111 again, or move to a different folder.

There is existing querying for album names.  You need to add quotes if the name contains a space e.g:

```
album: "Book Covers"
```

**Comment by RupertAvery** [comment]
With the latest release, you can now sort the album list (menu Albums > Sort), and see what albums images are members of in the info.

Still thinking of ways to show at a glance if an image in the thumbnail pane is in an album or not, as that would help when moving images into albums.

**Comment by RupertAvery** [comment]
The list of albums an image is a member of is now displayed in metadata.
