### ISSUE TITLE
image size in info box

### ISSUE THREAD

**Issue by laurentopia** [RupertAvery/DiffusionToolkit#127]
**Is your feature request related to a problem? Please describe.**
no knowledge of image size so not able to check which scale image was scaled up at

**Describe the solution you'd like**
add image size in info box

**Comment by RupertAvery** [comment]
I pull the image size from the parameters, this might be different from the actual image size, or might be missing. I can pull the actual image size, if that's what you need.

You will probably need to rebuild the database when I push the changes.

**Comment by laurentopia** [comment]
Ok, I will rebuild the db now...
metadata rebuilt

**Comment by RupertAvery** [comment]
Image size is now in info box
