### ISSUE TITLE
shift+right arrow doesn't go to the next row

### ISSUE THREAD

**Issue by laurentopia** [RupertAvery/DiffusionToolkit#128]
**Describe the bug**
left and right arrow go to next previous row when line end is reached
not shift_arrow

**Version:**
latest as of today

**To Reproduce**
press shift_ right arrow repeatedly

**Expected behavior**
selection switches to next row

**Comment by RupertAvery** [comment]
Notes: 

Seems to be caused by ThumbnailListView.SelectedIndex pointing to the first item in the selection instead of the current.

**Comment by RupertAvery** [comment]
Let me know if this version fixes the issue

[v1.2.2.zip](https://github.com/RupertAvery/DiffusionToolkit/files/12194152/v1.2.2.zip)

**Comment by laurentopia** [comment]
It works thank  you.
