### ISSUE TITLE
Retain copied parameter content in the Windows Clipboard when closing Diffusion Toolkit

### ISSUE THREAD

**Issue by ooofest** [RupertAvery/DiffusionToolkit#130]
**Is your feature request related to a problem? Please describe.**
Using the "Copy Parameters" feature, a user can copy a viewed image's SD metadata into the Windows Clipboard.

If the Diffusion Toolkit is then closed, that parameter data is apparently cleared from the Windows Clipboard during the exit process.

**Describe the solution you'd like**
Retain the copied parameter data in the Windows Clipboard during app exit, or at least provide an option to allow that behavior.

**Describe alternatives you've considered**
Turning on Clipboard history might be an alternative, but I tend to not utilize this in Windows.

**Additional context**
N/A

**Comment by RupertAvery** [comment]
Hi, Diffusion Toolkit does not do anything with the clipboard when exiting, so I'm not sure what's causing your problem.

I am unable to replicate the issue.  

Steps:

1. Open Diffusion Toolkit
2. Select an image and view info in Preview pane
3. Click Copy Parameters button in Preview pane
4. Close Diffusion Toolkit
5. Paste text in Notepad

Result:

Copied parameters are pasted in Notepad.

**Comment by ooofest** [comment]
Thanks for checking.  This stilll clearly happens on my Windows 10 Pro installation, unfortunately.

Is it possible that you have Windows Settings -> Clipboard -> "Clipboard History" enabled?  I do not have that enabled in this case.

**Comment by RupertAvery** [comment]
You're right.

Looks like I was using the wrong API for copying data to the  clipboard. I'll have the fix in the next release.

Thank you!
