### ISSUE TITLE
Recommending Case-Insensitive Search (i.e. for Model Hash)

### ISSUE THREAD

**Issue by tk101-fs** [RupertAvery/DiffusionToolkit#131]
It looks like some searches are case sensitive, which gives unexpectedly limited search results for some scenarios. For example, if an image metadata has a (notional) model hash of "abc123def", but I run a Model Hash search for "ABC123DEF", the image will not be found in the search. This is unexpected because the case of the ascii character should not matter -- the hash values are a segment from a SHA computation and while normally you find that written in all-CAPS, it appears some generation software writes the model hash in lower-caps to image metadata.

I recommend adjusting the search term comparison so that case-sensitivity is not a factor.

**Comment by RupertAvery** [comment]
Thank you. The fix will be included in the next release
