### ISSUE TITLE
[BUG] Clearing the filter on an album shows everything

### ISSUE THREAD

**Issue by acorderob** [RupertAvery/DiffusionToolkit#132]
**Describe the bug**
When on an album, if you clear the filter (even if you didn't filter anything before) you get everything, not just the images on the album. This persists even if you change albums or change to search/favorites.

**Version:**
1.2.1

**To Reproduce**
1. Click on an album.
2. Open the filter panel, click Clear and then Filter.
3. You get everything.

**Expected behavior**
You should get the images in the album without any other filtering.

**Comment by RupertAvery** [comment]
Thanks for finding this. I'll include the fix in the next release.

**Comment by RupertAvery** [comment]
Should be fixed in the latest release
