### ISSUE TITLE
Can you add a 'next page' button and keyboard shortcut?  

### ISSUE THREAD

**Issue by mattehicks** [RupertAvery/DiffusionToolkit#133]
Maybe Ctrl+ArrowKey?

**Comment by RupertAvery** [comment]
Right now, there is a button at the bottom right of the thumbnail area. It's shortcut (if you hover over it, it will show) is ALT + PageDown.

Is this what you need?

**Comment by mattehicks** [comment]
Thanks I appreciate that.
One issue is that while stable diffusion is running, there is constant
popups on Diffusion Toolkit saying "One image added"
But the popups are directly over the pagination buttons :)
Thanks!
