### ISSUE TITLE
[Enhancement] Make refreshing the Search results more intuitive

### ISSUE THREAD

**Issue by mattehicks** [RupertAvery/DiffusionToolkit#136]
SD is running, and I'm seeing the notifications in DT.  But no images are being added to the gallery.
The images do appear if I navigate a page forward, then back, they are there.
Sorry if this is the intended design, I'll close the ticket.

Info: Windows 10, newest DT build 1.2.1

Thanks!

**Comment by RupertAvery** [comment]
This is intended. It would be a bit jarring if you were navigating and the page refreshed. 

Use F5 or clicl the Search icon to see the latest images

**Comment by mattehicks** [comment]
What about when I click the 'refresh/reload' button?  Still, no images are being added.

**Comment by nateclowar** [comment]
Make sure you don't have anything in the search bar, I've made the mistake of having searched for something earlier...going to an album and search is then empty, but when you go back to a directory the search term is still active...and then it may not show your updated images when they dont match that search.

**Comment by mattehicks** [comment]
It seems if I hit the magnifier icon, I get the result I'm looking for.  New images added.  Thx.

**Comment by RupertAvery** [comment]
You should get the same effect if you press F5.  Refreshing the search results isn't too intuitive, I'll try to come up with something better.

**Comment by mattehicks** [comment]
Thanks for giving it some thought.  I'll just put my 2 cents here;  My use-case is that I would like to have DT up and tracking my recent generations, meaning "auto load", newest at the top.   
Maybe a toggle switch to turn it on, for those who need this?

**Comment by RupertAvery** [comment]
I think the last feature you requested has been implemented (auto refresh) so closing this for now
