### ISSUE TITLE
Support operations upon multiple pages of search results (Add to Album)

### ISSUE THREAD

**Issue by dejayc** [RupertAvery/DiffusionToolkit#138]
Not to be snarky, but is this project entering abandonware state?  Progress on the project seems to have completely halted after its initial burst of feature release.

Anyways, is there a way to perform bulk operations on all pages of paginated search results?  E.g. I search for a keyword that returns 30 pages of results, and I'd like to be able to move all 30 pages of images to an album.

**Comment by dejayc** [comment]
Thanks for the prompt reply, and good luck on settling in!

**Comment by RupertAvery** [comment]
I've added an option to add search results to an album. Tools > Search Results > Add search results to Album. You must have a active query or filter to do this (you can't add all images to an album)
