### ISSUE TITLE
[BUG] ? openclibboard failed (0x800401D0 (LCIPBRD_E_CANR_OPEN))

### ISSUE THREAD

**Issue by thijsi123** [RupertAvery/DiffusionToolkit#144]
**Describe the bug**
Pressing any copy button gives me openclibboard failed (0x800401D0 (LCIPBRD_E_CANR_OPEN)) and closes/crashes the app

**Version:**
v1.3

**To Reproduce**
Open the app, and press any copy button.

**Expected behavior**
Copy button should copy text to the clipboard and not crash/close the application

**Source Image**
Q: Does the error occur on a specific image?
A: No, it happens with any image.

**Source Image or Screenshots**
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/64159148/d5d13a2a-4d60-4fa9-956e-a1a0e859532e)

**Additional context**
WIndows 11 (Don't be fooled by the taskbar)
[DiffusionToolkit.log](https://github.com/RupertAvery/DiffusionToolkit/files/12838463/DiffusionToolkit.log)

**Comment by thijsi123** [comment]
I just tried v1.2.1 and it works on there.

**Comment by RupertAvery** [comment]
Seems to have been caused when switching to `Clipboard.SetText()` from `SetDataObject()`, as a measure of allowing the data to stay on the clipboard after the application exits. Looks like there's a way to do that with `SetDataObject(data, true)`, so I'll revert to that method.

**Comment by RupertAvery** [comment]
This should be fixed in the latest release
