### ISSUE TITLE
[BUG] album pane broken

### ISSUE THREAD

**Issue by acorderob** [RupertAvery/DiffusionToolkit#149]
**Describe the bug**
The album pane is broken. No albums are shown. Images do show their albums in the new info panel. Also, creating a new album does not add it to the images submenu until you restart the application.

**Version:**
1.4

**To Reproduce**
Just open the application when you have albums.

**Expected behavior**
Albums should be seen in the list. Creating a new album should add it to the submenu inmediately.

**Source Image**
N/A

**Source Image or Screenshots**
N/A

**Additional context**
N/A

**Comment by RupertAvery** [comment]
Is this starting from a new installation?

**Comment by acorderob** [comment]
It works. Both the album pane and the update of the submenu. Thanks.
