### ISSUE TITLE
Images not being imported

### ISSUE THREAD

**Issue by ImLunaHey** [RupertAvery/DiffusionToolkit#15]
Related to https://www.reddit.com/r/StableDiffusion/comments/zep6wl/diffusion_toolkit_updated_to_v05/izdusnz/?context=3 and #14 

Currently I have a folder called "unsorted" and inside of that is folder for each session.
Those session folders contain loads of jpeg + txt files.
Each image has a corresponding data file with the exact same name just different file extension.

When scanning the "unsorted" folder I get 100 or so out of 2k+ images. It does see the files but it doesn't import them.

**Comment by ImLunaHey** [comment]
One thing I am noticing is the file name for the txt can sometimes be cut off even if the jpeg has the full version.

![image](https://user-images.githubusercontent.com/105922175/206436690-32636fcd-f368-43c0-ba7d-a55bb2f63490.png)

**Comment by RupertAvery** [comment]
Can you attach the files somewhere so I can have something to work with?

**Comment by ImLunaHey** [comment]
This is the directory above.

[2022_12_06T12_47_06_287Z.zip](https://github.com/RupertAvery/DiffusionToolkit/files/10185079/2022_12_06T12_47_06_287Z.zip)

**Comment by RupertAvery** [comment]
Thanks, I'll take a look at it

**Comment by ImLunaHey** [comment]
Looks like this is likely the issue.

Images should match the start of the txt file name vs matching it exactly.

Wrote a small node program to scan all my images and it looks like any that don't have an exact match don't get picked up. If I change my program to match exactly I get the 112 results back just like toolkit does.

```json
{
        "imageFile": "D:\\robot-art\\unsorted\\1664455191596\\1996_01826a12_RealESRGAN_x4plus_anime_6B.png",
        "dataFile": "D:\\robot-art\\unsorted\\1664455191596\\1996_01826a12.txt"
    },
```

**Comment by RupertAvery** [comment]
Yes, that's how I'm getting it to work too.

**Comment by RupertAvery** [comment]
See if this fixes it

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/beta_v0.6.1

**Comment by ImLunaHey** [comment]
Good job!

![image](https://user-images.githubusercontent.com/105922175/206623129-3c0a5ee5-6ee2-46f0-9f2f-10a9022034ec.png)
