### ISSUE TITLE
Aesthetic Score: calcualte for images that do not have initially score saved

### ISSUE THREAD

**Issue by DmytroSokhach** [RupertAvery/DiffusionToolkit#151]
**Is your feature request related to a problem? Please describe.**
I have bunch of images that do not have "Aesthetic score"

**Describe the solution you'd like**
1. I'd like to have a plugin or menu that will allow calculate Aesthetic Score AND save it back into metadata.
2. From **DiffusionToolkit**
   a. **find** files by search criteria (like AestheticScore == null)
   b. **Apply custom command** for those files
3. From **DiffusionToolkit** _(sounds like min effort one)_
   a. **find** files by search criteria (like AestheticScore == null)
   b. **Export/Save** search list into file

**Describe alternatives you've considered**
1. maybe A1111 Extras can do it for batch of files, but I could not find how to do it
2. Custom Python script that will iterate folders and use https://github.com/vladmandic/sd-extension-aesthetic-scorer

**Additional context**
-

**Comment by Ariloum** [comment]
that aesthetic scorer got a python script named "aesthetic-scorer-cli.py" which you can use in the command line -
just feed it with a folder of images you want to score.
