### ISSUE TITLE
[BUG] Folder not updating after move

### ISSUE THREAD

**Issue by DrJimmyBrungus** [RupertAvery/DiffusionToolkit#152]
Latest version (1.4)

I am using the folders view to view my generated images, and then favourite / move them into a separate Saved folder.

The problem is, after moving the files (by selecting them either in the folder or from the favourites view, right clicking and selecting Move), the images still remain in the original folder within Diffusion Toolkit as if they had not been moved. Even after refreshing or reloading. 
Checking file explorer shows that the files have actually been moved.
If I open the Saved folder in DiffusionToolkit, I do not see the new images there.

To clarify, my folder structure is like so:

...Output\txt2img-images\2023-11\
..Output\Saved\2023-11\

The idea is to periodically use DiffusionToolkit to go through the txt2imag-images folders, favourite the pictures I want to keep, then open the favourites and move them all at once into the Saved folder. Then I can delete the leftover txt2img images.

**Comment by RupertAvery** [comment]
Thanks for the report. Folders is definitely a bit buggy as it was just shoehorned in.

I have a fix and it will be included in the next release
