### ISSUE TITLE
[BUG]Excluded Folder dont work

### ISSUE THREAD

**Issue by MinagiCN** [RupertAvery/DiffusionToolkit#153]
**Describe the bug**
Excluded Folder dont work

**Version:**
1.4`

**To Reproduce**
,for example folder A has a sub folder folder B,they all filled with pictures,and folderA is already in Diffusion Folders in settings.Then i set folder B a excluded folder,the pics in folderB still appears in software after settings saved or exit reopen the software ..

**Expected behavior**
Exclude folders inside Diffusion folders.

**Comment by RupertAvery** [comment]
To confirm, you initially scanned the images without the excluded folder, so they are now in the database, then you added excluded folder, so you want them to be removed from the database?

**Comment by MinagiCN** [comment]
> To confirm, you initially scanned the images without the excluded folder, so they are now in the database, then you added excluded folder, so you want them to be removed from the database?

YES exactly!you are right! 

software already scanned and show images without the excluded folder, they are now in the database, then add these folders to  excluded folder, images inside  excluded folder shold remove from the database.

**Comment by tetsuoo-online** [comment]
Here, that's the issue I was looking for.
I have a suggestion : Instead of making 1 single database, why not make several instead, one for each added folder (with an optional custom name). That way when you remove a folder it will simply ignore/delete the corresponding database.
What do you think ?

**Comment by MinagiCN** [comment]
thank you sooooooooooooooooooooo much i saw this fixed. im always support your project!! (heart)
