### ISSUE TITLE
Add Support For RuinedFooocus metadata

### ISSUE THREAD

**Issue by runew0lf** [RupertAvery/DiffusionToolkit#154]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Implement the metadata

**Describe alternatives you've considered**
No alternatives

**Additional context**
Example metadata:
`{"Prompt": " ffserenity,  Grit, Rust, Stains, concept art a spaceship inside an abandoned barn, covered in rust and cobwebs, digital artwork, illustrative, painterly, matte painting, highly detailed, ", "Negative": "photo, photorealistic, realism, ugly, ,  photo, photorealistic,realism, ", "steps": 30, "cfg": 5, "width": 1344, "height": 768, "seed": 2394374243, "sampler_name": "dpmpp_2m_sde_gpu", "scheduler": "karras", "base_model_name": "juggernautXL_version6Rundiffusion.safetensors", "base_model_hash": "7d723a7b", "loras": "Loras:<Objects\\Serenity_SDXL.safetensors \ud83d\uddd2\ufe0f:1>,<Detailers\\Grit-SDXL.safetensors \ud83d\uddd2\ufe0f:0.7>,<None:0.5>,<None:0.5>,<None:0.5>", "start_step": 0, "denoise": null, "software": "RuinedFooocus"}`

Link: [RuinedFooocus](https://github.com/runew0lf/RuinedFooocus)

**Comment by RupertAvery** [comment]
Cab you attach some sample images? I"ll need to find what PNG tags it falls under.

**Comment by runew0lf** [comment]
![2023-12-06_22-53-02_7768](https://github.com/RupertAvery/DiffusionToolkit/assets/9966016/dcc06330-cf52-4050-8928-3943d9ca3613)
![2023-12-06_14-33-07_4176](https://github.com/RupertAvery/DiffusionToolkit/assets/9966016/827d3245-088d-476f-b3d5-e9e3a803e08c)
![2023-12-05_22-57-31_7587](https://github.com/RupertAvery/DiffusionToolkit/assets/9966016/2bfe6fa3-2c1f-4fb4-9985-4bee755376d2)
![2023-12-05_12-21-15_7598](https://github.com/RupertAvery/DiffusionToolkit/assets/9966016/8ff58e5f-320c-4d51-85ae-1b1f40b33079)
![2023-12-05_10-41-42_4266](https://github.com/RupertAvery/DiffusionToolkit/assets/9966016/a9ebdf58-3f00-4055-8f9e-c74f7b99b6e2)

There we go dude!

**Comment by RupertAvery** [comment]
nice pics! thanks, I'll get the metadata in

**Comment by tetsuoo-online** [comment]
oh no. No no no no I shouldn't have updated. You did something yesterday ! xD
I can tell because the Show Info changed.
Now I can no longer see the Lora weights, so I can't compare the images parameters anymore using Diffusion Toolkit. And I was doing just that a few hours ago... :'(

**Comment by RupertAvery** [comment]
Can you give a sample of how it was before (v1.5) and how it is now?

I don't think I made any other changes than changing how it is displayed and adding separate seed/cfg/size/sampler
