### ISSUE TITLE
When webui creates a file, it is not automatically loaded from toolkit

### ISSUE THREAD

**Issue by skymagico** [RupertAvery/DiffusionToolkit#162]
**Is your feature request related to a problem? Please describe.**

When webui creates a file, it is not automatically loaded from toolkit,  even with the watch folders option turned on.
It only gets updated when I press the refresh button.

Windows 11, Diffusion toolkit 1.4 , webui version 1.7.0 python: 3.10.11 - torch: 2.0.1+cu118 - xformers: 0.0.20 - gradio: 3.41.2

**Describe the solution you'd like**

I want it to load automatically without pressing the refresh button
 I really need an answer, please.
The program is working great thanks

**Describe alternatives you've considered**

**Additional context**

**Comment by RupertAvery** [comment]
For some reason A1111 creates *.tmp files instead of images when generating, then renames to the proper extension. The original code was supposed to catch the newly generated image and add it specifically to a queue to process each image.  Since the filename must be correct (matching one of the extensions), the *.tmp file isn't considered as an image and is not processed.

I can change the code to run a full scan to detect all new images, but the code will detect any changes, including new non-images, which is less than ideal.

**Comment by skymagico** [comment]
Thank you for taking the time to reply while you were busy
I think 1.5.1 in the update list is related to this, but the update page
won't open. If it's made, I'd love to get it
Even if it's a beta test that's not the finished version, please let me use
it
I'm using the v1.4 version well

Postscript
When I made an image through webui, a deformed image came out, so if there
is a complete deletion function, it will be very helpful for file
management. Thank you

2023년 12월 28일 (목) 오전 3:55, David Khristepher Santos <
***@***.***>님이 작성:

**Comment by skymagico** [comment]
2023년 12월 28일 (목) 오전 3:55, David Khristepher Santos <
***@***.***>님이 작성:

**Comment by skymagico** [comment]
Thank you for taking the time to reply while you were busy
I think 1.5.1 in the update list is related to this, but the update page
won't open. If it's made, I'd love to get it
Even if it's a beta test that's not the finished version, please let me use
it
I'm using the v1.4 version well

Postscript
When I made an image through webui, a deformed image came out, so if there
is a complete deletion function, it will be very helpful for file
management. Thank you

**Comment by RupertAvery** [comment]
Please check the latest cersion

**Comment by skymagico** [comment]
Thank you very much
I'm satisfied with this update alone 
Personally, it would have been better if the image file was opened when the thumbnail was automatically loaded 
As you will collect opinions, there are also many deformed images when webui creates images. Every time, a complete deletion function is required immediately. I look forward to the next update 
Have a cup of coffee. Good luck with the end of the year

I'm using the program well. Thank you

**Comment by RupertAvery** [comment]
Thank you for the coffee!
