### ISSUE TITLE
[BUG] Text unreadable (too light) on light and system themes

### ISSUE THREAD

**Issue by aa956** [RupertAvery/DiffusionToolkit#166]
**Describe the bug**
Image description text is unreadable in Light and System themes.
Text and background colors are too similar.
Dark theme allows to read the text.

**Version:**
v1.5

**To Reproduce**
Open Diffusion Toolkit, select some image, try to read the generation parameters.

**Expected behavior**
Text and background colors to be different. E.g. text may be black if theme is Light or text color may use system text color if theme is System.

**Source Image**
Not related to the image

**Source Image or Screenshots**
Light theme font color:
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/27946957/5473ed93-5f6c-41ee-aa7f-a71f5de5aaaf)

Dark theme font color:
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/27946957/b5075d28-d518-431c-98e7-0d23438abcd3)

**Additional context**
Maybe related to Windows 11 Personalization / Colors settings of:

Apps: Light
Windows: Dark

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/27946957/50494e95-0c00-44da-aafe-68da99411470)

**Comment by RupertAvery** [comment]
Thanks, it's just some themeing issues I probably didn't check since I don't use light mode.

**Comment by aa956** [comment]
Thank you, fixed in master branch, just built and run, everything is readable now in both Light theme:

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/27946957/eef643b0-9858-4f6b-9ef2-81cd3d039191)

And System theme:

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/27946957/e7754a89-2c9d-44e4-9638-581cdcb8f799)

**Comment by Aamir3d** [comment]
This is happening on my system as well, with the default windows 10 theme.

**Comment by aa956** [comment]
> This is happening on my system as well, with the default windows 10 theme.

Workarounds for now:

1. Switch to the dark them in the app settings and wait for the next release that will include this fix
2. Check out the master branch and build it.

  - If you do not have .NET 6 SDK, download it here: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
  - Select Windows x64 SDK variant
  - Install the downloaded SDK.
  - Adapt the command from the `publish.cmd`, instead of publish use build:

```console
cd somewhere
git clone https://github.com/RupertAvery/DiffusionToolkit
cd DiffusionToolkit
dotnet build Diffusion.Toolkit\Diffusion.Toolkit.csproj -c Release -r win-x64 -o .\build --no-self-contained /p:PublishSingleFile=true /p:PublishReadyToRun=false /p:DebugType=None /p:DebugSymbols=false
```

You will have the new executable in `DiffusionToolkit\build`.
