### ISSUE TITLE
Remove images from metadata when folder is removed

### ISSUE THREAD

**Issue by Aamir3d** [RupertAvery/DiffusionToolkit#170]
I removed some folders from the folders list, but the image thumbnails were still in the metadata.

There should be an option to remove images from the database if the folder is removed.

**Comment by RupertAvery** [comment]
Thanks, I've added a tool to manually remove images from removed folders, as well as automatically remove images when a folder is removed.

**Comment by Aamir3d** [comment]
Thank you for the super fast update!
