### ISSUE TITLE
[BUG] Preview Horizontal Splitter position not saved

### ISSUE THREAD

**Issue by jonk999** [RupertAvery/DiffusionToolkit#171]
**Describe the bug**
Preview Horizontal Splitter position not saved was listed as fixed under bug 167, but doesn't appear to be.

**Version:**
1.51

**To Reproduce**
Open program.
Select an image to preview
Adjust the splitter position to show more/less of the image.
Close the program and reopen - splitter position is back at default taking half of the window

**Expected behavior**
When the splitter position is moved to show more/less of the image generation info, it will be in the same position when the program is next opened.

**Comment by RupertAvery** [comment]
I could have sworn it was working, but it turns out my code was entirely wrong.  Thanks

**Comment by RupertAvery** [comment]
If you don't mind, please test this version. Thanks!

[Diffusion.Toolkit.v1.5.2.zip](https://github.com/RupertAvery/DiffusionToolkit/files/13796932/Diffusion.Toolkit.v1.5.2.zip)

**Comment by jonk999** [comment]
Looks to be working now. Thank you so much for the quick turn around!
