### ISSUE TITLE
Support for InvokeAI .png metadata

### ISSUE THREAD

**Issue by jasoa** [RupertAvery/DiffusionToolkit#18]
Please add support for the prompt metadata added by InvokeAI's version of stable diffusion.  [https://github.com/invoke-ai/InvokeAI](https://github.com/invoke-ai/InvokeAI)  Older versions include a 'Dream' tEXt chunk in a plaintext cli command format and newer versions add an additional 'sd-metadata' tEXt chunk with json formatted prompt related data.

Examples below.  Hopefully the upload doesn't strip the metadata.

![013884 25711766 3914633383](https://user-images.githubusercontent.com/12177152/206618714-eacf2653-805e-4854-852c-dfb1a13edfc0.png)

![000344 3627653328](https://user-images.githubusercontent.com/12177152/206619216-3ba22ddf-46a1-45e0-9295-9bb2cba2f308.png)

**Comment by RupertAvery** [comment]
looks like the metadata is intact, thanks!

**Comment by RupertAvery** [comment]
This should be working in the latest release

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/beta_v0.7
