### ISSUE TITLE
[BUG] Unable to load DLL 'sqlite3' on recent builds

### ISSUE THREAD

**Issue by curiousjp** [RupertAvery/DiffusionToolkit#180]
**Describe the bug**
Following on from c9d6e16, attempts to build and run Diffusion.Toolkit now produce the following error:

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/48515264/7610e89e-db2e-44d6-9d20-d7deea64580a)

"Unable to load DLL 'sqlite3' or one of its dependencies: The specified module could not be found (0x8007007E)".

**Version:**
HEAD, currently [d6ac2ad](https://github.com/RupertAvery/DiffusionToolkit/commit/d6ac2adbd53f15d402068038abaec2f2fd9a3a03).

**To Reproduce**
Checkout the current version, and then perform a `dotnet run` in the Diffusion.Toolkit folder.

**Expected behavior**
Program should start and load the existing SQLite database without issue.

**Additional context**
Reversion to fc49cff fixes the issue.

**Comment by norville101** [comment]
It may be obvious to some, but my workaround for this was just to copy e_sqlite3.dll from a working build and rename it to sqlite3.dll.  Until things are fixed.

**Comment by RupertAvery** [comment]
This should be fixed in the latest build
