### ISSUE TITLE
Restore functionality auto-select first image

### ISSUE THREAD

**Issue by IxalonDarkstone** [RupertAvery/DiffusionToolkit#184]
In previous versions of the toolkit, the first image would be automatically selected and shown in the viewer.  For the past 2 versions I believe, this no longer happens. The new functionality that auto-refreshes is fantastic and works as expected, but without it auto-selecting the first image it becomes frustrating to have to click on the new image one by one as they are created. I'm not sure if there is a technical reason why this was removed from the product but this toolkit would be pretty much perfect for me if this functionality was added back or made an option in the preferences.

Thanks!
Ix

**Comment by RupertAvery** [comment]
Probably got lost in the code changes, or just wasn't implemented in a good way. I'll try to get this in the next release, Thanks!

**Comment by danrazor** [comment]
Please do not do that!!!
please do not show images as soon as the TOOLKIT opens as some of us do not work in safe for work environments.
keep this as option if you want. and let us opt out to show anything on start.
this is really scary.
regards

dan

**Comment by RupertAvery** [comment]
We can make this configurable.

**Comment by IxalonDarkstone** [comment]
Just wanted to stop by to thank you for making this available.  It truly makes your program perfect for me as I do a lot of x/y/z plots. Thanks so much!

**Comment by RupertAvery** [comment]
I've been wondering if the ability to "filter" by x/y would be useful. like, given a set of criteria to display along x/y, you could automatically filter images to appear in those slots. So, dynamic x/y plots without them being baked into a single image. And you could change the criteria on the fly.

**Comment by IxalonDarkstone** [comment]
Not sure I completely follow. Would this be like a dynamic filter where you can show only images that have seed x AND cfg 4? It seems like the current filtering should be able to do this, but I have noticed that the filter does not really work as expected. Even if I filter by nothing except the model (selected from the dropdown) I get no results. The only consistent filtering I can get to work is favorite filtering via the icon, and additional keyword filtering in the box at the top. So I can get all marked favorites that include the keyword catgirl.  If I put the model name or anything else in the filter it gives no results. This isn't a huge deal to me though so I haven't raised an issue.

**Comment by RupertAvery** [comment]
No, I mean a separate view dedicated to x/y plots. The search view only filters, but it can't align the images along x/y . I'd need to create a separate view for that.
