### ISSUE TITLE
[BUG] No information on the right pane

### ISSUE THREAD

**Issue by gohan2091** [RupertAvery/DiffusionToolkit#188]
**Describe the bug**
No information on the right pane

**Version:**
1.5.1

**To Reproduce**
Open the app and go to Diffusions window to view the folders you have added containing your images

**Expected behavior**
Right pane has information on the prompt, prompt negative and other settings

**Source Image**
N/A

**Source Image or Screenshots**
![Screenshot 2024-01-23 143732](https://github.com/RupertAvery/DiffusionToolkit/assets/127342824/a23aa4bc-1d35-4da4-a962-c8d949d20610)

**Additional context**
Was working fine 3 days ago, now cannot get it to work

**Comment by danrazor** [comment]
try 1.6 beta he release recently. it has few new GUI. few bugs like that. but try and see if that helps

**Comment by gohan2091** [comment]
> That's weird.
> 
> Try this:
> 
>     * Go to Edit > Settings > Database
> 
>     * Make a backup of the database, just to be safe (although we won't be making any changes to the database here)
> 
>     * Click Open Folder.
> 
>     * Important: Close DiffusionToolkit before you proceed.
> 
>     * rename config.json to config.bak
> 
>     * Open DIffusionToolkit
> 
>     * It should run as if it was a fresh install. However, your images are still in the database. Re-add your folders to be able to access them and see if it is fixed.
> 
> 
> Here's the latest beta version in case you are interested.
> 
> [Diffusion.Toolkit.v1.6 beta.zip](https://github.com/RupertAvery/DiffusionToolkit/files/14026643/Diffusion.Toolkit.v1.6.beta.zip)

That's fixed it! thanks so much! I will try the beta as well and see what's changed.
