### ISSUE TITLE
Watch for new images?

### ISSUE THREAD

**Issue by ImLunaHey** [RupertAvery/DiffusionToolkit#19]
Would be nice if we had either a quick scan or if the program would watch for new files being written.
Currently it takes a few minutes to scan 3k files and I'm sure that's just going to get slower over time.

Another option I had though of is skipping all files it's already seen, which I don't think it currently does.

**Comment by RupertAvery** [comment]
There are two buttons, Rescan folders and Rebuild images. 

Rescan folders does exactly what you need: searches for new images not yet in the database. It takes all the filenames in the database, compares it against all the filenames in your folders, removes the overlap, and scans what's left.

 It's quite fast against 16,000 images (almost instant on my SSD anyway, but let me know if it's slow on yours).  

You don't need to rebuild images unless I add a new metadata field that you want to search on, that your existing images might have, but are not yet in the database.

I know it's not clear, so I've added a dialog box when pressing Rebuild Images to this effect.  (not sure if it's in the latest release).

I'll try to make this distinction a bit more clear somehow.

https://github.com/RupertAvery/DiffusionToolkit/blob/master/Diffusion.Toolkit/Tips.md#updating-your-images

**Comment by RupertAvery** [comment]
I'll consider having a file system watcher if it works well, and if I can get some sort of notification working, or maybe check every n minutes.

**Comment by ImLunaHey** [comment]
You should be able to use `inotify` or something similar to watch a file path and it'll emit an event any time files are updated. I use type of thing in node in production and it works wonders.

**Comment by ImLunaHey** [comment]
So looking at this, nodejs I can get all my files indexed in less than 2s.
In this it takes over a minute for 4k or so files.

One thing to mention I'm doing this on a 5400RPM HDD not a SSD.

**Comment by RupertAvery** [comment]
Are you parsing the PNG parameters too?

To be clear, does Rescan folders work slowly for you?  

Note that Rebuild images is NOT needed unless you want to actually reparse the metadata of ALL your existing files. There is no need to do this unless I add support for a parameter that hasn't been parsed from your existing images.

I'll see if I can improve performance reading the metadata, if it's really that slow.

**Comment by RupertAvery** [comment]
So I tried this with an Seagate HDD 7200 RPM 2TB Barracuda hooked up as an external drive over USB.

With 3.9k images in 12 directories, I was able to  **Rescan folders** in negligible time.

![image](https://user-images.githubusercontent.com/1910659/206891729-6d3843f2-a79c-4662-855f-2abd8243ffe6.png)

You should not be using **Rebuild images** if you only want to add newly generated images.

I tried rebuilding images from an empty database and I was able to do the 3.9k images in around 2secs.

![image](https://user-images.githubusercontent.com/1910659/206891818-d0228223-90e7-4dd4-9708-b3ff82019416.png)

So, this could probably be attributed more to actual indexing for existing images.

**Comment by RupertAvery** [comment]
Watch folders implemented in the latest release

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/beta_v0.7
