### ISSUE TITLE
[Enhancement] Prevent removing images if root folder is inaccessible

### ISSUE THREAD

**Issue by danrazor** [RupertAvery/DiffusionToolkit#194]
**Jan 2024 Feature request #1**
Most important! The App should not start REMOVING images if a DRIVE is OFFLINE. it should ask if we want it to remove it or not. please understand this is very important. (clicking on offline folders and drive is also making the APP to CRASH.)
 I tried to uncheck [recursive] [watch folder] and everything but still, as soon the app starts, it deletes files from offline drives.
 please make it stop removing files from list.
 let the app ask us if we want to remove the offline images or not.
just like windows shortcut with missing files.

the App is assuming incorrectly that everything happens on a fixed drive and this is not the truth or reality.
because we have external drives and if toolkit removes an entry of images from a drive that is offline also removes Favorites and everything and this is really really unacceptable.

**Comment by RupertAvery** [comment]
The reason why this was done this way initially is because if a user deletes files from their hard drive, Diffusion Toolkit has no way of knowing that is was deleted.  A step was introduced to "clean up" in case it could not find the image.

We can remove this step, but users will now need a way to clean up missing files. There is a Tools function to do this, but users don't generally know this.

Instead of removing, we can still do a missing files check and warn the user on startup.

**Comment by danrazor** [comment]
I understand but the reality is that in this day and age, we tend to keep things on the external drives especially laptop users.
the whole point of DiffusionToolkit breaks apart as soon as it only serves local drives.

please understand the unique opportunity for the Toolkit right now.
People generate a lot of images, easily hundreds per day, may thousands.
some images we keep on local drives but most we keep offline on external drives.

we need an app that keeps the database information alive. 
Even if the images in the database are offline.
diffusionToolkit fits perfectly.
but as soon as it starts to clean up, it just kills its usefulness.

the solution is simple like any software like windows or aftereffects or any other.
just use a place holder as "image not FOUND" or "MEDIA offline".

imagine the heartbreak.

I make 100 albums and 1000 favorites on my external drive folders and next day i went to a friends home and opened DiffusionToolkit before i added external drive first.

BOOOM!
everything is gone! all my favorites and albums in a second!!!
because the app wanted to clean up.

so you see, the clean up is a very bad idea.

I have two solutions if you please be kind:

**A. use a place holder for missing media and an option in the settings for users if the want clean up or not.
B. Give us a database file sessions!!! how cool is that!
suppose i have an X drive. i attach the drive and opened the session for the X drive in TOOLKIT and i don't have to worry about loosing any favorites and albums anymore.
Toolkit just loads that session. 
like we do in a hard drive recovery software.**

so please please, do not clean up and remove offline images.
thanks

Dan

**Comment by danrazor** [comment]
Hi, any idea when the next update will drop?
the one i was using somehow stopped scanning new images. 
after the updater was flagged by Avast anti virus.
(it didn't quarantine it but said it is watching it and put a copy in (SANDBOX) folder)

i did multiple tries and seemed nothing worked.
then i checked that the older interface version was working.
so i copied the extension folder and diffusion.toolkit.db (database) folder from the older one and copy / replaced the new ones (new interface)
so, it seemed it works again. 
but
the threat of offline drive image removal is not letting me use it permanently. 
Thanks for the hard work.

cheers

Dan

**Comment by RupertAvery** [comment]
Here is a build of the current code.  Be advised that it's a beta and there may be some bugs. I think I've rooted out the important ones, as this version will move your folder settings from the json file into the db (this will allow database sessions since the root folders are now per-db)

This version will no longer remove images that are unreachable.  The root folder will be disabled and marked (Offline) in the folder treeview (it might still be clickable in the thumbnail view).

Images that can't be loaded will display  as "unavailable"

Once you reconnect your root folder, you can click the refresh button at the top of the folder treeview to have it available in Diffusion Toolkit

[Diffusion.Toolkit.v1.6.20240126.zip](https://github.com/RupertAvery/DiffusionToolkit/files/14068846/Diffusion.Toolkit.v1.6.20240126.zip)

**Comment by danrazor** [comment]
Awesome!
i will test and report back.
Cheers

**Comment by danrazor** [comment]
Hi, reporting again.
this version was working fine.
but as soon as i did a Show in explorer, AVIRA again captured the app and put it in quarantine.
says the app puts your security and data at risk.

please connect with AVIRA and let them know it is safe.
regards

**Comment by danrazor** [comment]
Another issue:
if i press CONTROL+SHFT+P to show/hide preview. it doesn't return back to normal THREE PANE view.

this is normal view.
**[FOLDERS]>[ICONS]>[Preview/information]** 
but if i click on the popout view then the preview and information from the main window disappears and we are left only with 

[FOLDERS] > [icons]
and now to view a bigger image, i have to use the separate pop out window. or restart the app which fixes it again.
and this issue was also present in the 0.9 which i tested earlier.
cheers

Dan

**Comment by danrazor** [comment]
Hi, 
here is another update.
it is either, not somehow searching for new images or if we add a new folder or some of the folders just do not show images.
A  Pop-up if we add a new folder and after 3 seconds when the folder is added "FORGEIGN KEY constraint failed"

in the main folder I have 
database files being created as per app RUN I believe?

Backup-20240131-020246.db
Backup-Migrations-20240131-013604.db

i want to ask, how do we use these files?
pick any one we want and replace the actual 

diffusion-toolkit.db

file in the main folder?
can i delete the ones I do not want?
what is the solution of not searching more folders after first run?
thanks

Dan

**Comment by danrazor** [comment]
Update.
I replaced the new database .db with an older one and now it seems to work with showing images in new added folders. 
but I feel it has not really indexed everything in the folder. because the list of the GB size is smaller than in my actual folder in explorer.
but!!! some of the files are getting duplicated entries in the DATE CREATED section???
and treated as two separate files but both point to same file in explorer.
i know this because if i make on NSFW and blur it, then the other one does not get blurred.
strangely, not all files are getting double entries.

**Comment by RupertAvery** [comment]
Can you check if this is still an issue in the official 1.6 build?

You may have to re-add  your folders (the images are still there, but the experimental builds you are using may have removed the folders from the settings config)
