### ISSUE TITLE
Hypernetworks used not showing

### ISSUE THREAD

**Issue by trihardseven** [RupertAvery/DiffusionToolkit#2]
So it seems the toolkit isn't picking up on hypernetworks. Also although it shows the model hash it would be nice if it also showed the model name for easier identification. 

Parameters on toolkit: 
![image](https://user-images.githubusercontent.com/54422205/205375206-d511c9e0-4d0b-4a02-ac0a-a48615201c55.png)

On image browser extension: 
![image](https://user-images.githubusercontent.com/54422205/205375337-df2eacc8-e486-4f69-87b8-f81c132dd33a.png)

**Comment by trihardseven** [comment]
Also batch size is also useful to have saved as it causes variations on images. Meaning if you do the same seed with batch size 2 vs batch size 3 the result might be different.

**Comment by RupertAvery** [comment]
Hypernetwork search shpuld be available now.

Make sure to Rebuild images to make sure existing images are parsed again for the new fields
