### ISSUE TITLE
[BUG] FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by skymagico** [RupertAvery/DiffusionToolkit#203]
**Describe the bug**
I was using version 1.6, but since a few days ago I am getting the error message "foreign key constraint failed"
 Only 2 out of 7 files are recognized when scanning a folder
Same thing with version 1.5
The same goes for the Diffusion Toolkit folder deleted and reinstalled

What should I do?  Thanks

**Version:**
What version of Diffusion Toolkit are you using?  1.5 and 1.6

**Tool:**
What tool did you use to generate the image?  A1111, 1.7.0 

![error](https://github.com/RupertAvery/DiffusionToolkit/assets/154529410/5f83429c-ce7c-42d7-85a4-50cc6a9410d1)
![오류](https://github.com/RupertAvery/DiffusionToolkit/assets/154529410/4f95fb7a-04f9-4254-9e33-b2b202e002f3)

**Comment by RupertAvery** [comment]
There was probably a database change when you updated to 1.6, which isn't officially released yet and can be very buggy. You should only do so for testing purposes.  Exactly when does this error occur? Is it on startup? What action causes it?

**Comment by skymagico** [comment]
At first, the symptom occurred when I deleted or moved files in Explorer, but now I can't scan even if I don't delete the files.  Is there a way?

**Comment by RupertAvery** [comment]
So now, it only occurs when you click scan?

Can you try remove excluded images or clean removed folders?

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/1910659/ccbf3fe3-c42a-4152-8ff7-1e67ed3873a2)

**Comment by skymagico** [comment]
Webui didn't load thumbnails in toolkit when file was created Autoscan didn't work
Manually scanning didn't work and I kept getting ""foreign key constraint failed"" error messages.

Can you try remove excluded images or clean removed folders?
I tried but no improvement

Luckily, I changed to Commits c7b8a63 and it seems to work now. 
It's nice to see the program working well

It must be a lot of work to make the program.
Good luck and thank you for your interest.
I don't mind if you close the issue.

**Comment by RupertAvery** [comment]
Please let me know if the latest version still has the issue (v1.6.1)

**Comment by skymagico** [comment]
It's working well. Thank you
