### ISSUE TITLE
[Feature request] please add information from TENSOR.Art files

### ISSUE THREAD

**Issue by danrazor** [RupertAvery/DiffusionToolkit#206]
HI,
I am using a website TENSOR.ART and it is very similar to Automatic 1111 and comfyUi.
the benefit is that it has all the information embedded in the PNG files.

but DiffusionToolkit is unable to sort the data in the PNG files correctly and only display partial data.

i am sharing  a sample of the data from the PNG files below for you to look.
_**Important model names and controlnet names in BOLD**_
and i am hoping you can use this to take the relevant information out of the PNG files and display better in the TOOLkit.
because of this drawback, i have to use PNGchunk.com website to view complete data from files.
Thanks for you hard work
looking forward for your response.

Dan
-----------------------------------------------------------------------------------
"Prompt
splatter style character painting of a solo,  black hair, man,  male focus,  sky,  cloud,  black eyes,  lips,  cloudy sky,  portrait,  face painted in oil paints with thick painterly strokes,  star \(sky\),  starry sky,  realistic, galaxy00,  , painting, artistic oil painting stick, oilpainting, High detailed , oil painting, oil paint, ink,  paint splatter and drips,  textured backdrop,  moody atmosphere,  blood splatter,<lora:EMS-274416-EMS:1.100000>

Negative Prompt

Sampler
DPM++ 2M Karras

Seed
2405514972

CFG scale
7.0

Steps
20

Size
904x1536

Model hash

Model
EMS-33097-EMS

RAW:
{
	"parameters": "splatter style character painting of a solo,  black hair, man,  male focus,  sky,  cloud,  black eyes,  lips,  cloudy sky,  portrait,  face painted in oil paints with thick painterly strokes,  star \\(sky\\),  starry sky,  realistic, galaxy00,  , painting, artistic oil painting stick, oilpainting, High detailed , oil painting, oil paint, ink,  paint splatter and drips,  textured backdrop,  moody atmosphere,  blood splatter,<lora:EMS-274416-EMS:1.100000>\nSteps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7.0, Seed: 2405514972, Size: 904x1536, Model: EMS-33097-EMS, Denoising strength: 0.8, Style Selector Enabled: True, Style Selector Randomize: False, Style Selector Style: base, Lora hashes: \"EMS-274416-EMS: 236e581116d3\", Version: v1.6.0.125-2-g82bee03, TaskID: 687150387467218522",
	"generation_data": {
		"models": [
			{
				"label": "v1.0",
				"type": "LORA",
				"modelId": "686522545119425959",
				"modelFileId": "686522545118377385",
				"weight": 1.1,
				**"modelFileName": "by nightPortraits-XL",**
				"baseModel": "SDXL 1.0",
				"hash": "FCE289CF3B2A846794ED55D840403070F5EF9B05D0768FC83511DB7CF66D5335"
			}
		],
		"prompt": "splatter style character painting of a solo, black hair,man, male focus, sky, cloud, black eyes, lips, cloudy sky, portrait, face painted in oil paints with thick painterly strokes, star \\(sky\\), starry sky, realistic,galaxy00, ,painting,artistic oil painting stick,oilpainting,High detailed ,oil painting,oil paint,ink , paint splatter and drips, textured backdrop, moody atmosphere, blood splatter, ",
		"negativePrompt": " ",
		"width": 904,
		"height": 1536,
		"imageCount": 1,
		"samplerName": "DPM++ 2M Karras",
		"steps": 20,
		"cfgScale": 7,
		"seed": "-1",
		"clipSkip": 1,
		"baseModel": {
			"label": "1",
			"type": "BASE_MODEL",
			"modelId": "632213924906971533",
			"modelFileId": "632213924905922958",
			**"modelFileName": "oil_paint",**
			"baseModel": "SDXL 1.0",
			"hash": "EC3C35A1476C7B86A7D44CE0D3BBD9601828282820B919C4B8381E95E085B298"
		},
		"images": [
			"https://7022ae40757f8d53295a57619de9b364.r2.cloudflarestorage.com/tensor-sf-sig/workspace/imagetoimage/659974922768136056/c6bef8e5-90b6-46f4-9899-9efe3c9890ed.png"
		],
		"denoisingStrength": 0.8,
		"sdVae": "vae-ft-mse-840000-ema-pruned.ckpt",
		"controlnet": {
			"enableControlnet": true,
			"args": [
				{
					"inputImage": "https://tensor-sf-sig.7022ae40757f8d53295a57619de9b364.r2.cloudflarestorage.com/workspace/imagetoimage/659974922768136056/37d2a364-097c-4411-a9d0-de2506851743.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0bef8a003dc93fc4d7030c9da79271ff%2F20240126%2F%2Fs3%2Faws4_request&X-Amz-Date=20240126T093421Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=d992a9ae6eb91446e3829a26dea8673b5f22177bda25193025ceb75ef9f0c77e",
					"module": "none",
					**"model": "control_v1p_sdxl_qrcode_monster",**
					"weight": 1,
					"guidanceEnd": 1
				}
			]
		},
		"sdxl": {},
		"workEngine": "TAMS_V1"
	}
}

--------------------------------------------------------------------------------------

**Comment by RupertAvery** [comment]
Please provide around 3 actual images so that I can test on my end. Thanks.

**Comment by danrazor** [comment]
![08b8a517-6257-4c16-905b-31d78ad47c36](https://github.com/RupertAvery/DiffusionToolkit/assets/41794256/56de5b88-dd95-41cf-91bd-7095e91dc45d)
![nRQg5FvuCJSvyclvwc3F3](https://github.com/RupertAvery/DiffusionToolkit/assets/41794256/5522dd1d-5c49-494d-b939-662c6d78a431)
![686059878369829063](https://github.com/RupertAvery/DiffusionToolkit/assets/41794256/ee88534b-0d39-44a1-85d4-281b00e31955)
