### ISSUE TITLE
[BUG] New added files to folders are listed twice

### ISSUE THREAD

**Issue by danrazor** [RupertAvery/DiffusionToolkit#207]
Hi,
New images added to the folders in explorer are now appearing twice if REFRESH (Scan for new folder is used)
I tried rebuilding the entire database and it took its time to rebuild it but still the images already showing twice remained as it is.
both images points to the same ORIGINAL image in EXPLORER.
and this is happening to new images since last week or so.
older and the first scanned images do not show duplicate entries.

and no, the folder is not added twice.
I have just one folder added as a ROOT folder of my X:drive.
the new generations are placed in folders as per date or by subject.

**Comment by RupertAvery** [comment]
Duplicates should be removed so this should not happen again. Please confirm
