### ISSUE TITLE
Found a [BUG] whenever I move the bar that splits the preview window and the metadata

### ISSUE THREAD

**Issue by f-rank** [RupertAvery/DiffusionToolkit#208]
**Describe the bug**
If I move the split that divides the preview and the metadata, next time when I restart the app, the preview and metadata windows are nowhere to be seen. This is happening if the app is started on a 4k monitor, on a 2k and a 1080 this doesn't happen. 
I'll link how the config files changes and the values under each state.

config file Working:
https://pastebin.com/5V0SduXS

config file Not Working:
https://pastebin.com/ZFxtxkxC

**Version:**
1.5.1

**To Reproduce**
Start app in 4k monitor, move preview/metadata splitter

**Expected behavior**
nothing should disappear, everything should remain in place in optimal homeostasis.

**Comment by RupertAvery** [comment]
Can you check if this fixes the issue?

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/7855752123/artifacts/1235591850

**Comment by f-rank** [comment]
Can confirm fix is valid.
