### ISSUE TITLE
[Enhancement] Detect file type by Magic instead of file extension

### ISSUE THREAD

**Issue by maxwell1755** [RupertAvery/DiffusionToolkit#210]
**Describe the bug**
Many of my images from novelAI are not appearing in the software at all. Typically, these are older images and ones with a random string/uuid for the title, whereas old images with the prompt for a title work fine. However, this is not always the case. I've noticed that some newer images are unable to be handled as well, specifically ones that I have uploaded to MEGA and redownloaded despite all of their metadata being intact

I believe this is due to many files being .jpg or .jpeg because I have had a similar problem before with another program. Changing the file extension to .png seems to fix it, but is unrealistic to do with all files. While working with ImageRanger support on this issue, they suggested it was due to "the files being encoded as a .png, with a different file extension"

**Version:**
custom installation of 1.6 so that "date created" sorts by "date modified" instead. Problem persists on the latest 1.6 release

**Tool:**
NovelAI

**To Reproduce**
Unknown, but I can provide problematic files

**Expected behavior**
all novelAI images should be handled properly

**Affected Image(s)**
An older problematic image:
![a4c01ead-58ad-4b2c-8a4e-df14f55b6a91](https://github.com/RupertAvery/DiffusionToolkit/assets/67136352/1dbc3605-836e-4d50-b807-c83fc4e4fbb2)
An even older one:
![70a78e62-f75e-4b19-9ea7-767291f2c6ea](https://github.com/RupertAvery/DiffusionToolkit/assets/67136352/e9103290-68ec-4214-92a0-fe81f2b68254)
newer problematic image: 
![9323be5c-602b-4cab-9af4-9863b30cb4a3](https://github.com/RupertAvery/DiffusionToolkit/assets/67136352/a9b0b6c3-6c09-4b2f-b4f3-c84b4c127d16)

**Comment by RupertAvery** [comment]
That's strange, the images appear on my setup.

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/1910659/18008a8e-4984-4e2c-add7-56a7b2e497e4)

**Comment by RupertAvery** [comment]
Can you check it this fixes your problem?

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/7859182787/artifacts/1236063359

**Comment by maxwell1755** [comment]
right now it's giving "An unhandled exception occurred: Value cannot be null. (Parameter 'element') on my PC. This is likely a result of interfering with a previous version because it works fine on my laptop. As soon as i figure out how to get around this I will update

**Comment by maxwell1755** [comment]
preliminary results seem flawless, I don't have the time to do a thorough check but no large chunks are missing. And there's even an option to sort by date modified! Unless I find something I'll mark this as closed, thank you so much!
