### ISSUE TITLE
[Enhancement] Have separator between vertical view panes - v1.6

### ISSUE THREAD

**Issue by jonk999** [RupertAvery/DiffusionToolkit#212]
**Is your feature request related to a problem? Please describe.**
In V1.6, when you select View, Folder or View, Album, etc the pane that opens doesn't fill the entire vertical space. As such, I thought that not all folders or albums were showing until I noticed the scroll bar.

**Describe the solution you'd like**
Either have a visible separator when only or more one of the view options is selected and the entire vertical pane isn't used.
Or have the view use the vertical space available on the pane depending on how many options are selected.

**Comment by RupertAvery** [comment]
Can you see if this is better?

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/7855752123/artifacts/1235591850

The navigation panels will now expand to take all the space of the items inside.  There is only one scroller for now.

**Comment by jonk999** [comment]
I downloaded the version at the link provided and when I run it I get the following error:
`An unhandled exception occurred. Value cannot be null (Parameter 'element')`

When I 'ok' the error the program then closes.

However, it appears to be fixed in the version from https://github.com/RupertAvery/DiffusionToolkit/issues/211 where the entire pane is now filled.

**Comment by RupertAvery** [comment]
This should now be working better in the latest official version (v1.6.1)

Navigation panes are now resiziable, and the last pane will always take the full height available. Also, `Value cannot be null (Parameter 'element')` errors should be fixed
