### ISSUE TITLE
Support for SDNext image metadata

### ISSUE THREAD

**Issue by iDeNoh** [RupertAvery/DiffusionToolkit#214]
**Is your feature request related to a problem? Please describe.**
No problem, but it would be nice to be able to use this with images generated with SDNext

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
None 

**Additional context**
Here are some example images that have metadata
![00016-20240208001903](https://github.com/RupertAvery/DiffusionToolkit/assets/1209382/540d22b4-a1e3-46a6-8945-011e2766a4d5)
![00026-20240208152350](https://github.com/RupertAvery/DiffusionToolkit/assets/1209382/8156b163-4b47-40ab-9492-42d56aeadb73)
![00056-20240205205319](https://github.com/RupertAvery/DiffusionToolkit/assets/1209382/f0dc2269-332d-4355-9d8f-4592d7324c57)

**Comment by RupertAvery** [comment]
Have you tried loading these in Diffusion Toolkit?

It looks like it already supports it, maybe because it is a fork of A1111?

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/1910659/581dd332-e379-4f4d-95b0-6ef64ef2b69b)
