### ISSUE TITLE
[BUG] Error unique contraint failed: Image.Path after update

### ISSUE THREAD

**Issue by Eleksar387** [RupertAvery/DiffusionToolkit#217]
**Describe the bug**
After the update, when I open DiffusionToolkit I get this error

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/64690088/4b153a72-03e8-49bd-84f7-f3a894b48700)

After hitting OK the program closes.

**Version:**
1.6

It worked without problems before the update.

**Comment by RupertAvery** [comment]
Can you see if this fixes the issue?

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/7862299250/artifacts/1236543376

If not, I may need you to run some queries on your database.
