### ISSUE TITLE
Allow searching by seed?

### ISSUE THREAD

**Issue by ImLunaHey** [RupertAvery/DiffusionToolkit#22]

**Comment by RupertAvery** [comment]
There's no wiki yet, I don't want to have to update 2 documents when adding features.

There is in-app documentation for that.

https://github.com/RupertAvery/DiffusionToolkit/blob/master/Diffusion.Toolkit/Tips.md#geting-started

Basically add seed: <number> in your query or seed: <number>-<number> to search a range of seeds
