### ISSUE TITLE
[BUG] Album add / create problem

### ISSUE THREAD

**Issue by Aamir3d** [RupertAvery/DiffusionToolkit#224]
I created an Album (example: Cyborgs)

However, I am unable to add images to this album through the Diffusions by selecting some images and right clicking > Add to album. It always asks me for a new Album name.
(Also thinking about long term - what happens when a user adds a lot of albums).

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/122131887/44c129b9-e542-44db-8346-15e62c101e1b)

**Comment by Aamir3d** [comment]
Addendum: After closing and restarting the application, and refreshing the files, the following options now appear. I am unsure why this bug appeared though.

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/122131887/246ebcc9-8207-45fb-b475-d60ad14b1c0f)

**Comment by RupertAvery** [comment]
Thanks, I'll jave to check again what happens if there are no albums initially.

**Comment by Aamir3d** [comment]
> Thanks, I'll jave to check again what happens if there are no albums initially.
> 
> The behavior is, it will show the first 10 albums, and the last updated one will always be on top.
> 
> It's more convenient to just drag images to albums.

Thanks @RupertAvery !!
Problem is though, that all the thumbnails are on the left, while one main image is on the right (with the prompt data). There is no way to drag a selection unless there is an album pop out or drop box on the right.

**Comment by RupertAvery** [comment]
There is view > albums (navigation pane).

**Comment by Aamir3d** [comment]
> There is view > albums (navigation pane).

Thanks @RupertAvery - for some reason I never used the top menu :-(  . I'm going to retry doing this.
