### ISSUE TITLE
Feature request: add autoupdate

### ISSUE THREAD

**Issue by konqiDAM** [RupertAvery/DiffusionToolkit#23]
Hi, I would write a PR my self (wanted to) but I don't have much time. But you can add a file on your git repo that indicates actual version number then on startup check against your version on program and then it asks user if he want to update. If you want full auto update then you can add a line to the version number pointing to last TAG and download, so you can get the zip and uncompress it.

**Comment by RupertAvery** [comment]
Looks like the URL in question is https://api.github.com/repos/RupertAvery/DiffusionToolkit/tags, ok I'll try it.

**Comment by RupertAvery** [comment]
It's implemented. Does some inital testing and it should work. Maybe you could do some testing too? change the local version.txt and then allow it to "update"

**Comment by konqiDAM** [comment]
It worked fine for me, it downloaded the new version when lowering the number

**Comment by RupertAvery** [comment]
Thanks, closing the issue
