### ISSUE TITLE
[BUG] App crashes with "Sequence contains no elements" when pressing F or N while no image is selected yet

### ISSUE THREAD

**Issue by NoahStolk** [RupertAvery/DiffusionToolkit#242]
**Describe the bug**
The app crashes with "Sequence contains no elements" when pressing `F` or `N` while no image is selected yet. I believe I tested most shortcuts and these were the only ones that cause the crash. `0-9`, `I`, and `B` work fine.

**Version:**
1.6.1

**To Reproduce**
1. Open the app
2. Don't select any image yet
3. Press F or N

**Comment by RupertAvery** [comment]
Thanks for reporting.

**Comment by RupertAvery** [comment]
This build should have the fix. If you can test it and some other features, it would be greatly appreciated, thanks!

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/10442192936/artifacts/1824889263

**Comment by NoahStolk** [comment]
Can confirm this build fixes it. 👍 It also fixes some of the issues I had with albums before. Thanks! I have not found any other problems, but will open a new issue if I do.
