### ISSUE TITLE
[BUG] Show in Explorer for Folder

### ISSUE THREAD

**Issue by Mohsyn** [RupertAvery/DiffusionToolkit#248]
"Show in explorer" for folder results in opening of Desktop Folder instead of parent of selected folder

**Comment by RupertAvery** [comment]
This build should have the fix. If you can test it and some other features, it would be greatly appreciated, thanks!

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/10442192936/artifacts/1824889263
