### ISSUE TITLE
Error when deleting a source of images

### ISSUE THREAD

**Issue by konqiDAM** [RupertAvery/DiffusionToolkit#25]
![image](https://user-images.githubusercontent.com/44301655/207554032-9aa24f30-0c49-41fd-99ef-5a838504ab76.png)

**Comment by konqiDAM** [comment]
Also thinking about it... I have google drive synced and maybe I moved around some folder and that caused the issue instead the delete and it was just coincidence

**Comment by RupertAvery** [comment]
Strange, I can't replicate the issue

* Select a fodler
* Click Remove Folder
* Folder is removed
* Close Settings
* No errors

**Comment by RupertAvery** [comment]
Might have been the watch-folders running.  In that case it may have nothing to do with the settings dialog, so I'll close this for now.
