### ISSUE TITLE
[BUG] Unable to refresh to include new images

### ISSUE THREAD

**Issue by Aamir3d** [RupertAvery/DiffusionToolkit#255]
On pressing the refresh button, new images are not pulled from the folders.
The message on the bottom says "Scan started" then "Scan Complete" without adding the images.
**Version:**
1.7

**Tool:**
Forge, Comfy

**To Reproduce**
Clicked the 
![image](https://github.com/user-attachments/assets/7e2fa793-cfe9-456b-ac44-3f5c1cb7b81b)
Refresh button and also tried Ctrl+F5 to refresh, but new images don't appear.

**Comment by RupertAvery** [comment]
Do you have previous images that worked? Or are they all new images?  Can you post some example images here?

**Comment by Aamir3d** [comment]
> Do you have previous images that worked? Or are they all new images? Can you post some example images here?

So I created new images in Comfy. The folder is in the paths (Settings > Diffusion folders)

I hadn't used Diffusion toolkit in about 2-3 weeks when I last refreshed the images (12th August to be precise) and all images were included/synced (Previous release).
Once I saw the release note today, I upgraded to the latest version and pressed the sync/refresh button to get the images I've been creating the past few weeks. However, it does not import them for some reason.

**Comment by RupertAvery** [comment]
That's strange. I've seen other issues about images not loading at all for new users.  It all seems to run fine on my setup, using ComfyUI and A1111, however, I generate on one machine and just copy the files into my local, and it picks it up with watched folders.

AHA. It seems that watched folders bypasses the process. I can recreate the issue now.

**Comment by RupertAvery** [comment]
Can you try this:

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/10570167410/artifacts/1857454833

**Comment by Aamir3d** [comment]
> Can you try this:
> 
> https://github.com/RupertAvery/DiffusionToolkit/actions/runs/10570167410/artifacts/1857454833

Thanks - will update with testing after a few hours when I'm back.

**Comment by Aamir3d** [comment]
Thank you for your effort and quick resolution! Confirming the release you shared can add new images.
![image](https://github.com/user-attachments/assets/9cd08bd8-2da9-42ad-8e46-3b82ab6ebabc)
