### ISSUE TITLE
Empty folders no images

### ISSUE THREAD

**Issue by cristian-tapia** [RupertAvery/DiffusionToolkit#256]
**Describe the bug**
After adding the folders all I can do is browse through them, but no images are shown.

**Version:**
1.7

**Tool:**
A1111, Forge, Comfy, Invoke

**To Reproduce**
Installed the software, add the diffusion folders, navigate.

**Expected behavior**
I expected to see some images

**Affected Image(s)**
Does the error occur on a specific image? If applicable, provide the actual image that is causing the problem. Github does not strip metadata from images so you can upload it directly here.

**Screenshots**
![Captura de pantalla 2024-08-26 110020](https://github.com/user-attachments/assets/a79f06e5-8afc-49f1-a1e3-4e2cb00b97ce)

**Additional context**
Maybe I'm doing something wrong? I'm new to Diffusion Toolkit. Thank!

**Comment by RupertAvery** [comment]
When asked, did you allow Diffusion Toolkit to scan your image folders? It needs to read in the images into its database first, before they appear in the folders.  You can try clicking the ![image](https://github.com/user-attachments/assets/21bee556-9a7d-4282-b464-df2be234f022) button, or Edit > Rebuild metadata

**Comment by cristian-tapia** [comment]
> When asked, did you allow Diffusion Toolkit to scan your image folders? It needs to read in the images into its database first, before they appear in the folders. You can try clicking the button on the left, or Edit > Rebuild metadata.

Hi, I was never asked for permission to scan any folder. If I remove the folders and add them again, yes, I'm, asked to scan them, but it says "scan complete" and no images are shown. Clicking on the button to rescan does nothing either.

> Can you also try clicking on Tools > Folders > Fix missing images?
Doing that gives me a message on the bottom right corner reading "0 files were updated"

Thanks in advance for any additional tips!

**Comment by RupertAvery** [comment]
I saw someone else on reddit with a similar problem. Can you try with an older build for now?

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/v1.6.1 was the last stable one.

**Comment by ryders333** [comment]
[DiffusionToolkit.log](https://github.com/user-attachments/files/16753691/DiffusionToolkit.log)

**Comment by RupertAvery** [comment]
Looks like I didn't see the problem because I had watched folders enabled, and this somehow bypassed the bug.

**Comment by ryders333** [comment]
![Uploading 00000-327028823.png…]()
some small sample images

**Comment by cristian-tapia** [comment]
> I saw someone else on reddit with a similar problem. Can you try with an older build for now?
> 
> https://github.com/RupertAvery/DiffusionToolkit/releases/tag/v1.6.1 was the last stable one.

Thank you! That version worked 👍

**Comment by RupertAvery** [comment]
There is a fix for new users.  

To ensure you start from scratch, go to %APPDATA%\DiffusionToolkit and delete `config.json` and `diffusion-toolkit.db`. 

Then download this version and try to run it.

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/10570167410/artifacts/1857454833

**Comment by ryders333** [comment]
did not work, all folders are empty again.

**Comment by RupertAvery** [comment]
Strange, I've tested it several times, and just now again. Deleted config and db, then started it. Asked to Scan, said yes, then it had all the images.

If you don't mind, can you try again from a clean setup (you can rename your existing config and db and then name them back later if you need).  Then check if there are any log messages?

**Comment by ryders333** [comment]
[DiffusionToolkit.log](https://github.com/user-attachments/files/16756346/DiffusionToolkit.log)
it worked, selected folder, scanned, found images, thank you.

**Comment by RupertAvery** [comment]
Log looks clean, glad to know it worked for you! Thank you for running these tests.
