### ISSUE TITLE
Feature: Search GUI

### ISSUE THREAD

**Issue by RupertAvery** [RupertAvery/DiffusionToolkit#29]
A panel or popup that lists the parameters you can search on using fields, so you can create a query without typing.

Mostly as an aide for people who haven't yet memorized the searchable parameters.

A checkbox next to each parameter enables it.

Have dropdowns for stuff like hashes, samplers, taken from values actually the database.

Should be able to parse the current query

**Comment by Eleksar387** [comment]
Searching by models, steps, samplers, etc. would be great!

**Comment by RupertAvery** [comment]
@Eleksar387 note that you can already do this in Diffusion Toolkit, by adding these in the search bar

<prompt> model hash: <hash> steps: <value> sampler: <sampler name>

https://github.com/RupertAvery/DiffusionToolkit/blob/master/Diffusion.Toolkit/Tips.md#advanced-searching

**Comment by Eleksar387** [comment]
@RupertAvery Ups. Sorry. I am that old guy who really should know better: reading the docs helps 😳

**Comment by RupertAvery** [comment]
no worries

**Comment by RupertAvery** [comment]
Implemented in v0.9
