### ISSUE TITLE
Could you please support NovelAI's pnginfo format?

### ISSUE THREAD

**Issue by toshi-miura** [RupertAvery/DiffusionToolkit#3]
NovelAI's pnginfo is in a different format than webui's pnginfo and is currently not searched.

NovelAI's pnginfo is in the following format.

sample1
-----------------------------------------------------------------------------------------------
Title

AI generated image

Description

masterpiece,best quality,flat color,offical art,white theme,{{ultra-detailed}}, {{illustration}}, {{an extremely delicate and beautiful harbour city}}, {{an extremely delicate and beautiful girl with golden pupil}}, {{+++++}}, {{blue hair}}, //four ponytail,{{{{{long shot}}}}}, {{{{{golden eyes}}}}}, {{++++++}}, {{{{{{{{{{low twintails}}}}}}}}}}, //super fucking beautiful,++++{{very long sleeves}}, //

Software

NovelAI

Source

Stable Diffusion 81274D13

Comment

{"steps": 23, "sampler": "ddim", "seed": 4028746890, "strength": 0.69, "noise": 0.667, "scale": 12.0, "uc": "text,nsfw, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digits, fewer digits, cropped, worth quality ,low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, bad feet, realistic,3d,(large breast), long neck, bad arms, lowres, multiple people, animals, missing legs, huge person, optical_illusion, upper body, profile"}
-----------------------------------------------------------------------------------------------

sample2
-----------------------------------------------------------------------------------------------
Title

AI generated image

Description

1girl,alone,single,solo,only one,one character,{{{{{{Personage as the main perspective}}}}}}, {{{{{{character in the middle}}}}}}, {{{{masterpiece}}}}, {{{{best quality}}}}, {{ultra-detailed}}, {{illustration}}, clear-cut margin,alphonse mucha, extremely detailed CG unity 8k wallpaper,{{{{an extremely delicate and beautiful}}}}, {{dynamic angle}}, An enchanted forest at night illuminated by glowing mushrooms, {{{{Tyndall effect}}}}, {{Fluorescent mushroom forests background}}, 1girl,{{arms behind back}}, {{beautiful detailed eyes}}, cute pink eyes,golden pupil,detailed face,upper body,white dress,messy floating pink hair,disheveled hair,focus,{{beautiful water}}, river,flying butterfly,sunlight,shine,chiaroscuro, ray_tracing,{{painting}}, [[[[[[[[[[[[8 k artistic photography]]]]]]]]]]]],

Software

NovelAI

Source

Stable Diffusion 81274D13

Comment

{"steps": 50, "sampler": "ddim", "seed": 3611012530, "strength": 0.69, "noise": 0.667, "scale": 4.5, "uc": "{{{{two girls}}}}, ,lowres,badanatomy,badhands,badfoots,wrong,badfingers,text,error,missingfingers,extradigit,fewerdigits,cropped,worstquality,lowquality,normalquality,jpegartifacts,signature,watermark,usemame,blury,badfeet,futa,futanari,small_penis,yaoi,huge_breasts,large_breasts,three legs,wrong hand,wrong feet,wrong fingers,deformed leg,abnormal,malformation,lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,bad art, ugly, messy drawing, flesh pile,deformed, bad anatomy, disfigured, mutation, mutated, extra limbs, fat, obese, missing limb, floating limbs, disconnected limbs, long neck, long body, part of the head, poorly drawn feet, mutated skeleton, long skeleton, bad proportions, mutated hands and fingers, intricate human hands fingers, poorly drawn hands, malformed hands, bad hands,poorly drawn face, poorly drawn asymmetrical eyes, big ears, mutated face,extra nipples,tits, huge breast,Inverted mountain, low-quality, flowers, grass,distorted mountain, distorted light, low-quality light, low-quality mountain, low-quality illustration, low-quality background,"}
-----------------------------------------------------------------------------------------------

**Comment by toshi-miura** [comment]
I'm attaching it for your reference as I think you will need the file for testing when you develop it.

![1girl,alone,single,solo,only one,one character,{{{{{{Personage as the main persp s-3611012530](https://user-images.githubusercontent.com/1235065/205416995-52fee3bc-6962-4574-af2a-8ceb3dc13e14.png)
![1girl,alone,single,solo,only one,one character,{{{{{{Personage as the main persp s-4110054908](https://user-images.githubusercontent.com/1235065/205417001-ba4a355f-ec97-483
![{{best quality}}, masterpiece, {{best illuminate, best shadow}}, {{best illustra s-1896169205](https://user-images.githubusercontent.com/1235065/205417022-358fab11-6eae-4c82-a258-293f8057fbe2.png)
f-b8cb-2424573bbd92.png)

**Comment by RupertAvery** [comment]
I'm adding support for this and here's what it looks like:

![image](https://user-images.githubusercontent.com/1910659/205421217-a6743950-ed20-42bb-97b3-0c6a687f2dc5.png)

**Comment by toshi-miura** [comment]
Oh, that's great. Thank you.
I don't have a build environment at hand, so I'm looking forward to the release

**Comment by toshi-miura** [comment]
I used the latest version right away and it works very well.
Thank you very much.

**Comment by RupertAvery** [comment]
Thank you!
