### ISSUE TITLE
Auto111 Metadata should be parsed from JPGs as well

### ISSUE THREAD

**Issue by JustMaier** [RupertAvery/DiffusionToolkit#32]
Just saw this [conditional limiting image parsing to PNG](https://github.com/RupertAvery/DiffusionToolkit/blob/df78a1a6bcf9022ab106a6a5e4589dcfa1875025/Diffusion.Scanner/Metadata.cs#L33) and thought I'd let you know that AUTO 1111 actually records metadata in JPGs as well, just in the exif comments section. Here's an [example from Civitai](https://github.com/civitai/civitai/blob/72895720d89f8451fd38c451fffaeaccd444c150/src/utils/image-metadata.ts#L15).

**Comment by RupertAvery** [comment]
Thanks, this will be fixed in the next release.
