### ISSUE TITLE
Unable to gather Aesthetic score from images processed through uscaling. 

### ISSUE THREAD

**Issue by lync11** [RupertAvery/DiffusionToolkit#33]
I cant get it to find png info from a non ai generated image that has been upscaled with extra tab. It can gather how much its upscaled. The png info tab on auto1111 can gather the aesthetic info.

**Comment by RupertAvery** [comment]
Can you attach a sample image here?  The metadata is intact if uploaded here.

**Comment by lync11** [comment]
![00006](https://user-images.githubusercontent.com/5209312/208324937-dec67c1e-bffc-4426-8acc-5e3857c642c1.png)

**Comment by RupertAvery** [comment]
Thank you, I see the problem, I was throwing away the metadata if there was no prompt. Note that since there is no other metadata, you can only search by path and aesthetic score

**Comment by lync11** [comment]
Im eagerly waiting for the next release then. Your tool could be really useful for filtering a dataset by aesthetic score.

**Comment by RupertAvery** [comment]
PLease see latest release

**Comment by lync11** [comment]
Awesome, thanks. Merry Christmas.
