### ISSUE TITLE
Crash on soft/hardlinks in the models folder

### ISSUE THREAD

**Issue by vkleinmp** [RupertAvery/DiffusionToolkit#38]
I'm sharing my models over multiple webuis and also have a backup folder for the less used models onto more cheap harddrives. There are some NTFS soft and hardlinks to them and DiffusionToolkit crashes on start upon looking into them. Please fix.

**Comment by RupertAvery** [comment]
What error message pops up? Can you attach the log file?

**Comment by vkleinmp** [comment]
Sorry, I'm an idiot, it's crashing on symbolic links (from another harddrive) not on the hard-/softlinks (files on same volume).
Error look like:
White box (An unhandled exception occured)
Could not find a part of the path
'C:\Temp\Automatic1111\stable-diffusion-webui\models\Stable-diffusion\custom-model.ckpt'
with only OK button
on accepting immediate crash

**Comment by RupertAvery** [comment]
I have a symbolic link setup as below

![image](https://user-images.githubusercontent.com/1910659/210189623-116f292b-647d-430b-8520-247a5f03a052.png)

Created using:

```
mklink tron-legacy.ckpt "C:\models\Tron-Legacy-Style-trnlgcy.ckpt"
```

The symbolic link is in "D:\conda\AUTOMATIC1111\stable-diffusion-webui\models\Stable-diffusion\linked", so in a different drive.

Is this the same as your setup?  

It is able to load.

![image](https://user-images.githubusercontent.com/1910659/210189697-408152a8-20c6-4717-968b-b6369d561a9f.png)

**Comment by RupertAvery** [comment]
Closing as there has been no updates and no other similar concerns
