### ISSUE TITLE
Proposed feature: Show preview at 100%

### ISSUE THREAD

**Issue by Eleksar387** [RupertAvery/DiffusionToolkit#39]
It would be nice to have an option not to scale the preview window to available screen size but restrict it to 100%. On large screens the preview get very pixelated.

Maybe it would be also nice to allow for adjustable thumbnail sizes and even disable the preview at all. So e.g. you could use 512x512 for "thumbnails" and disable the preview.

**Comment by RupertAvery** [comment]
Preview now displays at 100%

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/beta_v0.8.3

**Comment by Eleksar387** [comment]
I am now on 0.8.4. But it does not work for me. Preview is still full screen height. Neither mouse scroll nor CTRL++/- is doing anything. I am also wondering what that thing on the upper right is doing. Doesn't react when I am clicking on it.

![image](https://user-images.githubusercontent.com/64690088/210413091-1a59dcfc-b605-4463-a952-d204daa5d7d4.png)

**Comment by RupertAvery** [comment]
This should be fixed correctly now with the latest version. There is an option in View > Fit to Preview.  With the option unchecked, it will no longer stretch to the preview area but correctly display at 100%.

**Comment by Eleksar387** [comment]
Marvelous! Works perfectly.

Just an idea: Maybe a shortcut like CTRL+1 (like photoshop) to reset it to 100%. 
Also the possibility to increase the thumbnail size like in irfanview or lightroom would be nice.

**Comment by RupertAvery** [comment]
Ah, I had it mapped to CTRL-0 (like chrome)

**Comment by RupertAvery** [comment]
Thumbnail size is implemented.
