### ISSUE TITLE
Add aesthetic scoring

### ISSUE THREAD

**Issue by rodrix3855** [RupertAvery/DiffusionToolkit#4]
AWESOME job!
It would be great if you add searching via aesthetic score, which is added by an extension of SD Automatic1111.
This extension scores images on how beautiful they are from 0 to 10.

It would be fantastic to filter the images with a score range.

**Comment by RupertAvery** [comment]
Please see release v0.4.

**Comment by Rodrix33333** [comment]
Wow that's amazing. Will try it soon . Thanks

**Comment by Rodrix33333** [comment]
I got an idea. Could you add mass delete to all images with aesthetic score lower than X? And possibility of manually overriding the preset value.That would be an awesome feature. 

You could mass produce 500 images then have your app delete all bad ones.
