### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by f-rank** [RupertAvery/DiffusionToolkit#40]
v 0.8.1

Getting unhandled exception and config.json shows:

https://pastebin.com/Jtm54ysS

if I delete config.json so that it gets recreated and contains this:

https://pastebin.com/xJGnsQqW

all is good again, until some point in time when it throws the exception again.

**Comment by nicknack23** [comment]
Ditto. (Was just going to raise this issue myself.)

**Comment by RupertAvery** [comment]
Please try the latest version with better logging and post the stacktrace here (in DiffusionToolkit.log)

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/beta_v0.8.3

**Comment by f-rank** [comment]
Will do, soon as it happens.

**Comment by RupertAvery** [comment]
The actual error seems to occur when reading the window pane sizes, when the current region does not use decimal point (.) as a decimal separator.  This should be fixed. Please update and let me know if there is still a problem.

**Comment by f-rank** [comment]
> 

Will do case it happens.
