### ISSUE TITLE
Proposed feature: Show all images, even those lacking metadata

### ISSUE THREAD

**Issue by nicknack23** [RupertAvery/DiffusionToolkit#41]
Currently (AFAIK) DiffusionToolkit only finds images with valid metadata. It would be useful for organizing our image folders if the app could find other images as well. Maybe put [NO_METADATA] in the metadata area or just leave it blank. Then we could search for [NO_METADATA] and move files around based on whether they are stable diffusion images or not.

**Comment by RupertAvery** [comment]
The latest version now allows scanning images without metadata.

The corresponding filter is `nometadata: true` or` nometa: true`

**Comment by nicknack23** [comment]
Fantastic, thank you! Confirmed working for me.
