### ISSUE TITLE
Removing dir that exists in settings creates unhandled exception

### ISSUE THREAD

**Issue by f-rank** [RupertAvery/DiffusionToolkit#43]
![image](https://user-images.githubusercontent.com/1836566/210392962-626e141a-d35f-467f-afe6-b2f7e6c80d58.png)

If a directory that is listed in Diffusion Folders gets deleted, the next time the application starts it throws.

**Comment by RassilonSleeps** [comment]
You can solve this by deleting the `C:\Users\Utilzador\AppData\Roaming\DiffusionToolkit\diffusion-toolkit.db` file
Then edit the config.json in the same folder and remove the line that references the 'Desktop\test' folder.
It should be fine after that.

**Comment by RupertAvery** [comment]
Thanks for logging. Makes sense. I'll put this as a low-priority

**Comment by f-rank** [comment]
> 



> You can solve this by deleting the `C:\Users\Utilzador\AppData\Roaming\DiffusionToolkit\diffusion-toolkit.db` file
> Then edit the config.json in the same folder and remove the line that references the 'Desktop\test' folder.
> Then just use the rebuild images button in the ui, It should be fine after that.

... or just recreate the directory, start app and remove it from settings.
