### ISSUE TITLE
Proposed Feature: Move/Rotate preview

### ISSUE THREAD

**Issue by RassilonSleeps** [RupertAvery/DiffusionToolkit#44]
I use a vertical secondary monitor and would love to see the option to change the preview window to underneath the thumbnails.
When I throw DT on my vertical, I end up using it like this:
![Screenshot 2023-01-03 081436](https://user-images.githubusercontent.com/64247429/210396193-1826ab06-6de0-4810-888a-e48eeb9753e8.png)
but non-portrait images leave a lot of unused space as shown.
If it isn't to difficult, I was thinking something like this as a toggle option:
![DT-concept](https://user-images.githubusercontent.com/64247429/210408990-a6d841f7-f9a1-410c-bcf2-43d76e02aa0f.png)

**Comment by RupertAvery** [comment]
I'm planning to handle this by making the preview pane pop out.

![image](https://user-images.githubusercontent.com/1910659/210681079-3c44649f-33bb-4e5a-84ef-86238d6722ed.png)

You can then arrange the windows by hovering over the maximize button.

It's not ideal, but additionally allows you to view the preview full screen on one monitor.

I haven't figured out the best way to allow changing layouts without duplicating all the controls in different positions.

**Comment by RassilonSleeps** [comment]
A pop out pane option is a far better solution, with the benefit of using Windows 11's window snapping and/or PowerToys FancyZones and you indicated. 
You're quick to push commits for people, very much appreciated!
I look forward to the release, marking as closed.

**Comment by RupertAvery** [comment]
This feature is now available in the latest release
