### ISSUE TITLE
FeatReq: Wrap-around navigation when using arrow keys

### ISSUE THREAD

**Issue by cgessai** [RupertAvery/DiffusionToolkit#45]
When navigating with arrow keys, wrap to previous row last column or next row first column, depending.  This would allow continuous movement through thumbnails with left/right arrow keys only.

**Comment by RupertAvery** [comment]
ListView navigation doesn't seem to support that kind of behavior, at least not out of the box, which is a huge shame.

The best I can get it to work so far is:

Using arrow keys: selection will wrap around to the opposite edge when going past the current edge. It will not wrap to the next / previous row.

Using tab: selection will wrap around to the next row when going past the current edge. However, shift-tabbing makes it select multiple items while moving backwards.

**Comment by cgessai** [comment]
KK.  I appreciate you looking into it and thanks for the additional info!
