### ISSUE TITLE
Blank thumbnail images

### ISSUE THREAD

**Issue by Chubler-XL** [RupertAvery/DiffusionToolkit#46]
Looks like if a search returns more than about 1300 images it ends up with blank thumbnails.  Thumbs are blank from then on, even if a search returns a handful of images:

![image](https://user-images.githubusercontent.com/29263741/210640695-7cf95f6c-4f20-40af-abd1-18d002cd66ea.png)

**Comment by RupertAvery** [comment]
Definitely not a number of results issue, as I have over 17,000

![image](https://user-images.githubusercontent.com/1910659/210649543-3dfaf30d-8ee9-42c9-8938-ac32417e7ad3.png)

Are you on the latest version?

**Comment by Chubler-XL** [comment]
Yes, v 0.8.5.  Could be a corrupt image causing it I suppose - I'll do some more investigation.

**Comment by RupertAvery** [comment]
Great to know! Thanks, will be closing this for now.
