### ISSUE TITLE
Feature request: support WEBP files. (Partial code provided.) 

### ISSUE THREAD

**Issue by r7vz9h3** [RupertAvery/DiffusionToolkit#48]
Automatic1111's WebUI natively supports saving images with prompts in metadata as WEBP. The WEBP format is great for saving a lot of space compared to PNG or JPG, with minimal quality loss. WEBP files are also much faster to read and write than PNG.

I wrote a short script for indexing and searching prompts, where I used a function copied from Auto's code (`run_pnginfo`) to extract prompts from PNG and JPG, but it didn't work for WEBP for me, so I wrote my own line of code to extract prompts from these files. I linked to the relevant part of code:

https://gist.github.com/r7vz9h3/008e86bed8a4cbe4079e644ac71ccfc3#file-findgens-py-L72

All I needed was:
```py
with open(webp_image_path, 'rb') as imfile:
    info = imfile.read().decode('utf-8', 'ignore').rpartition('UNICODE')[2].replace('\x00', '')
```
I'm sure this can be improved a lot, but it worked in my script just fine.

**Comment by RupertAvery** [comment]
webp is supported in v0.9. For existing setups, add .webp to Settings > General > File Extensions
