### ISSUE TITLE
You must install or update .NET to run this application

### ISSUE THREAD

**Issue by AlUlkesh** [RupertAvery/DiffusionToolkit#51]
I downloaded the latest release, but can't seem to get this to run. I get:

![image](https://user-images.githubusercontent.com/99896447/212470213-7a783f8c-9cae-4aa0-8277-d6aa346d39e3.png)

I have installed the version that I get from that link, it's slightly newer:
```
C:\tools\Ai>dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.13
  Architecture: x64
  Commit:       1af80ba017

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
But I still get the same error message.

Do I need 6.0.0 exactly or what could be the issue?

**Comment by RupertAvery** [comment]
Have you tried installing the .NET 6.0 Desktop Runtime?

You may have just the .NET Core runtime 6.x installed.

Your Microsoft.WindowsDesktop.App is at version 5.0.13

**Comment by AlUlkesh** [comment]
Yes, that was my mistake. It's working now.

Thanks for the quick help!
