### ISSUE TITLE
Support moving images folder

### ISSUE THREAD

**Issue by space-nuko** [RupertAvery/DiffusionToolkit#56]
I know it says in the readme that all DiffusionToolkit metadata will be lost if you move the images folder, but the fact is, I often want to do this to save space. I have two different drives, one for generating and one for archiving, and also the folders get huge so I want to move them away to improve Explorer performance

It sucks that I have to choose between losing all my favorites and having a folder with 150,000 files that takes 30 seconds for Explorer to refresh when I generate something with txt2img

**Comment by RupertAvery** [comment]
There's a way to do this now, but only for selected files, so 100-500 images at a time.

Here's a proposed solution:

First set a query or filter (using the new Search GUI in v0.9). Then there will be a new menuitem Tools > Move matching files.

You select that and choose the folder you want to move all matching files to.

All matching files will then me moved to that folder, updating the paths.  If the paths are not in the list of folders, then any changes will not be detected within them.

Is this okay?
