### ISSUE TITLE
Proposed Feature: AIBooru Tags System

### ISSUE THREAD

**Issue by Lute-4** [RupertAvery/DiffusionToolkit#57]
AIBooru github:
https://github.com/aibooruorg/aibooru

**Comment by RupertAvery** [comment]
Hi, I appreciate your creating an issue, however, in the interest off creating interest to people who would be reading, please add information on what specific feature you'd like and how it benefits you, and how it would be integrated into the system from your point of view.

Thanks.

**Comment by RupertAvery** [comment]
woops

**Comment by RupertAvery** [comment]
Hi, I appreciate your creating an issue, however, in the interest off creating interest to people who would be reading, please add information on what specific feature you'd like and how it benefits you, and how it can be integrated into the application from your point of view.

Thanks.
