### ISSUE TITLE
Is it possible to drag and drop files from thumbnails?

### ISSUE THREAD

**Issue by toshi-miura** [RupertAvery/DiffusionToolkit#6]
The reason for this is that both novelAI and webui have the ability to read generated information by dragging files. This is because of the ability to drag a file and read the generated information.

webui pnginfo
![image](https://user-images.githubusercontent.com/1235065/205478426-7a779223-7768-47d1-b272-b07ebeace1fd.png)

The reason for this is that both novelAI and webui have the ability to read generated information by dragging files.

Therefore, we would be very grateful if we could do the following quickly.

Search for the file with this tool and click on
Drag the file from the thumbnail
Batch load generated information (prompt, scale, model, etc.) in each tool

**Comment by RupertAvery** [comment]
So, you want to drag from Diffustion Toolkit thumbnail into the WebUI PNGInfo?

Yes, this is possible. 

I've just implemented it, it seems to be working, I'll make it available in the next release.


![dragdrop](https://user-images.githubusercontent.com/1910659/205482082-70c19fb1-58cd-44d9-a88a-bda5f0d9a5da.gif)

**Comment by RupertAvery** [comment]
The feature is available here:

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/beta_v0.4.1

**Comment by toshi-miura** [comment]
Thank you for the quick implementation and pre-release. I downloaded it immediately and am grateful to be able to use it.
