### ISSUE TITLE
Unable to "build in" preview back into main window

### ISSUE THREAD

**Issue by vredin** [RupertAvery/DiffusionToolkit#60]
For unclear reason I clicked on "floating preview window" and now it shows in this way
![image](https://user-images.githubusercontent.com/417490/216047803-d0247a35-d009-4746-92ea-b00bc6343460.png)
And now I'm unable to return how it was before. 

If I press "show/hide preview" main window becomes unclearly wide
![image](https://user-images.githubusercontent.com/417490/216048068-cf7a196b-7939-44f6-9586-0cb3478038e1.png)
You can see that filers button in this case even disappears somewhere behind the screen
![image](https://user-images.githubusercontent.com/417490/216048699-fcf4ca90-4b08-4711-bbb3-8664869376fc.png)

**Comment by RupertAvery** [comment]
Hi,

I can't seem to find the cause of the issue, and I cannot replicate it. What screen resolution are you using?

You can try this to fix it though.

1. Exit Diffusion Toolkit
2. Go to `%APPDATA%\DiffusionToolkit` in Explorer
3. Open `config.json` 
4. Change the following lines to these values:
```
  "MainGridWidth": "1*",
  "MainGridWidth2": "1*",
```
5. Start Diffusion Toolkit

**Comment by vredin** [comment]
screen resolution is 2560x1600

Thanks, that
 "MainGridWidth": "1*",
  "MainGridWidth2": "1*",
helped

**Comment by RupertAvery** [comment]
Does it happen again when you popout the preview?
