### ISSUE TITLE
BUG: scanning unlisted folders

### ISSUE THREAD

**Issue by lavalava45** [RupertAvery/DiffusionToolkit#63]
In the program setting, I have only one directory containing my images and its main SD output directory contains all generated images. But the search button also shows other images from another local drive and absolutely another folder (unlisted in program settings). It's true that the folder contains SD images - but it is not listed in the app settings. I don't use hard or soft symlinks. So it really strange - why do Diffusion Toolkit scan other hard drives and list absolutely unrelated images? Thanks.

EDIT: I manually deleted the database file (diffusion-toolkit.db) and moved all images to another drive to remove them from the program search results.

**Comment by RupertAvery** [comment]
It does not scan other hard drives. It shouldn't anyway.  Does the problem occur again?
