### ISSUE TITLE
Request: load gallery on startup.

### ISSUE THREAD

**Issue by mattehicks** [RupertAvery/DiffusionToolkit#65]
I'd like to be able to reload the 'diffusions' gallery without having to click all the popups.
Is it possible to move those messages to a info bar or something?

Let me know if I can help - I am a SE as well,
cheers!

**Comment by bonzianimarazzi** [comment]
it would be very useful

**Comment by mattehicks** [comment]
This is a no-brainer

**Comment by RupertAvery** [comment]
This is implemented in v1.0
