### ISSUE TITLE
Proposed Feature: sort by attribute (e.g. "aesthetic_score")

### ISSUE THREAD

**Issue by bonzianimarazzi** [RupertAvery/DiffusionToolkit#66]
Hi,
it would be very useful to sort the attributes in ascending or descending order (and not just filtering)
do you think it could be possible?
Thanks

**Comment by vmunhoz** [comment]
I was searching for this in the documentation and did not find anything about it. It is a very important feature. I was trying to sort by aesthetic score.

**Comment by RupertAvery** [comment]
I am adding Sort by Date Created/Aesthetic Score/Rating on Ascending/Descending in the next release (either this week or next)

![image](https://user-images.githubusercontent.com/1910659/232351034-9e8bd630-3492-475e-ad8e-488b21cef14b.png)
