### ISSUE TITLE
Mass delete via filter 

### ISSUE THREAD

**Issue by Rodrix33333** [RupertAvery/DiffusionToolkit#7]
You are incredible.

Thanks for implementing my previous request.

I got an idea. Could you add mass delete to all images with aesthetic score lower than X? And possibility of manually overriding the aesthetic value.That would be an awesome feature.

Imagine this workflow: we could mass produce 500 images then have your app delete all bad ones, with aesthetic value!

Thanks a million again!!

**Comment by RupertAvery** [comment]
I'd rather have a standalone rating than override the aethetic score, i.e. overwrite what's in the PNG., unless you want to use this overridden value outside of Diffusion Toolkit. There is already some infrastructure in place already to store the rating, I just need to decide if it's 1-10, 1-5, and how to display it on screen without cluttering the UI.

I'll think about deleting. Maybe have some sort of filtering selector that tags all matches for deletion, then you can go in and review what was selected.

**Comment by Rodrix33333** [comment]
1-10 gives more freedom to users.

It would be nice to override the aesthetic score if it is wrong and just work with this score as the default score, that is used as your intial starting score.

You could have a delete button for all filtered photos.

**Comment by RupertAvery** [comment]
Kind of implemented in v0.9

Search via query or use a filter, then go to Tools > Mark all matching files for deletion.  When satisfied,  Edit > Empty Recycle Bin
