### ISSUE TITLE
Exclude Folders from Search

### ISSUE THREAD

**Issue by NorTroll** [RupertAvery/DiffusionToolkit#70]
is it possible to exclude certain folders within the folders you want to search? if not, is that something that would be difficult for some1 with little experience coding to implement?

**Comment by RupertAvery** [comment]
Yes, this was a feature I was planning to add anyway.

**Comment by RupertAvery** [comment]
Sorry, do you mean exclude from watched folders, or exclude from search?

**Comment by NorTroll** [comment]
> Sorry, do you mean exclude from watched folders, or exclude from search?

I am not entirely sure. 

Lets say you have folder A
With subfolders AA, AB, AC, AD, AE
With folders nested inside those again, following the same naming convention.
Let us say i have alot of temp images or trash images that my SD ui generates, that i do not want diffusion toolkit to see, or watch, or even know exists. 
Right now it always catalogs lets say AAD, and AAE, within AA and there is no way for me to exclude those folders.

Not sure if this made sense in any way, as i do not know how to explain it well

**Comment by RupertAvery** [comment]
This feature is already in v1.1, let me know if this is what you need. 

There is an option in settings to add excluded folders.

You can of course only exclude nested folders.
