### ISSUE TITLE
Chinese problem

### ISSUE THREAD

**Issue by xam0482** [RupertAvery/DiffusionToolkit#71]
Prompt word in Chinese is garbled
Unable to find Chinese in filter

**Comment by RupertAvery** [comment]
Please upload a sample image (PNG) with chinese prompt here, or paste the full prompt here so I can test, thanks

**Comment by RupertAvery** [comment]
Looks like this issue is caused by a bug in the Metadata Extractor library. I will provide a fix in the next release (1.2)

**Comment by RupertAvery** [comment]
Fix for this will be included in next release
