### ISSUE TITLE
Support ComfyUI metadata

### ISSUE THREAD

**Issue by jaythespacehound** [RupertAvery/DiffusionToolkit#72]
Would you be willing to support metadata generated by Comfyui?
Apologies if this is already working somehow and I've missed it but I didn't get metadata when I tried with v0.9
Attached is a generated image. Prompt was:
-----
```
best high quality
(cat:1.2) sitting on a log in a forest
cat has (long:0.9) (black:1.3) fur
```
-----
----- clip (rejection) ----
```
(out of frame)
black and white
bad eyes
```
-------

Here's offset 33 from pngchunks:
```
33 | 00 00 04 d0 74 45 58 74 70 72 6f 6d 70 74 00 7b 22 33 22 3a 20 7b 22 69 6e 70 75 74 73 22 3a 20 7b 22 73 65 65 64 22 3a 20 31 31 30 32 36 37 36 34 30 33 36 33 34 39 30 39 2c 20 22 73 74 65 70 73 22 3a 20 32 30 ... 79 70 65 22 3a 20 22 45 6d 70 74 79 4c 61 74 65 6e 74 49 6d 61 67 65 22 7d 7d 88 3a fb f5 | Data length: 1 232 bytesType: tEXtName: Textual dataAncillary (1)Public (0)Reserved (0)Safe to copy (1)CRC-32: 883AFBF5 | Keyword: promptText string: {"3": {"inputs": {"seed": 1102676403634909, "steps": 20, "cfg": 8.0, "sampler_name": "dpmpp_2m", "scheduler": "normal", "denoise": 1.0, "model": ["4", 0], "positive": ["6", 0], "negative": ["7", 0], "latent_image": ["14", 0]}, "class_type": "KSampler"}, "4": {"inputs": {"config_name": "v1-inference.yaml", "ckpt_name": "model.ckpt"}, "class_type": "CheckpointLoader"}, "6": {"inputs": {"text": "best high quality\n(cat:1.2) sitting on a log in a forest\ncat has (long:0.9) (black:1.3) fur", "clip": ["4", 1]}, "class_type": "CLIPTextEncode"}, "7": {"inputs": {"text": "(out of frame)\nblack and white\nbad eyes", "clip": ["4", 1]}, "class_type": "CLIPTextEncode"}, "8": {"inputs": {"samples": ["3", 0], "vae": ["4", 2]}, "class_type": "VAEDecode"}, "9": {"inputs": {"filename_prefix": "ComfyUI", "images": ["8", 0]}, "class_type": "SaveImage"}, "10": {"inputs": {"image": "Untitled-1 (1).png", "choose file to upload": "image"}, "class_type": "LoadImage", "is_changed": "677f93c5b52bd8fa7184ea65546bdf4b39af8252f40c9242f3cb02efe5fde6c9"}, "12": {"inputs": {"pixels": ["10", 0], "vae": ["4", 2]}, "class_type": "VAEEncode"}, "14": {"inputs": {"width": 512, "height": 512, "batch_size": 20}, "class_type": "EmptyLatentImage"}}
-- | -- | -- | --

```
And actual image:

![ComfyUI_04617_](https://user-images.githubusercontent.com/3013142/226129576-603c1e5e-d563-4894-8272-7351630133e2.png)
33	00 00 04 d0 74 45 58 74 70 72 6f 6d 70 74 00 7b 22 33 22 3a 20 7b 22 69 6e 70 75 74 73 22 3a 20 7b 22 73 65 65 64 22 3a 20 31 31 30 32 36 37 36 34 30 33 36 33 34 39 30 39 2c 20 22 73 74 65 70 73 22 3a 20 32 30 ... 79 70 65 22 3a 20 22 45 6d 70 74 79 4c 61 74 65 6e 74 49 6d 61 67 65 22 7d 7d 88 3a fb f5	
Data length: 1 232 bytes
Type: [tEXt](https://www.w3.org/TR/2003/REC-PNG-20031110/#11tEXt)
Name: Textual data
Ancillary (1)
Public (0)
Reserved (0)
Safe to copy (1)
CRC-32: 883AFBF5
Keyword: prompt
Text string: {"3": {"inputs": {"seed": 1102676403634909, "steps": 20, "cfg": 8.0, "sampler_name": "dpmpp_2m", "scheduler": "normal", "denoise": 1.0, "model": ["4", 0], "positive": ["6", 0], "negative": ["7", 0], "latent_image": ["14", 0]}, "class_type": "KSampler"}, "4": {"inputs": {"config_name": "v1-inference.yaml", "ckpt_name": "model.ckpt"}, "class_type": "CheckpointLoader"}, "6": {"inputs": {"text": "best high quality\n(cat:1.2) sitting on a log in a forest\ncat has (long:0.9) (black:1.3) fur", "clip": ["4", 1]}, "class_type": "CLIPTextEncode"}, "7": {"inputs": {"text": "(out of frame)\nblack and white\nbad eyes", "clip": ["4", 1]}, "class_type": "CLIPTextEncode"}, "8": {"inputs": {"samples": ["3", 0], "vae": ["4", 2]}, "class_type": "VAEDecode"}, "9": {"inputs": {"filename_prefix": "ComfyUI", "images": ["8", 0]}, "class_type": "SaveImage"}, "10": {"inputs": {"image": "Untitled-1 (1).png", "choose file to upload": "image"}, "class_type": "LoadImage", "is_changed": "677f93c5b52bd8fa7184ea65546bdf4b39af8252f40c9242f3cb02efe5fde6c9"}, "12": {"inputs": {"pixels": ["10", 0], "vae": ["4", 2]}, "class_type": "VAEEncode"}, "14": {"inputs": {"width": 512, "height": 512, "batch_size": 20}, "class_type": "EmptyLatentImage"}}

**Comment by RupertAvery** [comment]
Sure, I can support it

**Comment by RupertAvery** [comment]
Can you post some more sample images (3-5) so I can test as well?

For reference: this is the contents of the PNG tag in your image above:

```
prompt: {
  "3": {
    "inputs": {
      "seed": 1102676403634909,
      "steps": 20,
      "cfg": 8.0,
      "sampler_name": "dpmpp_2m",
      "scheduler": "normal",
      "denoise": 1.0,
      "model": [
        "4",
        0
      ],
      "positive": [
        "6",
        0
      ],
      "negative": [
        "7",
        0
      ],
      "latent_image": [
        "14",
        0
      ]
    },
    "class_type": "KSampler"
  },
  "4": {
    "inputs": {
      "config_name": "v1-inference.yaml",
      "ckpt_name": "model.ckpt"
    },
    "class_type": "CheckpointLoader"
  },
  "6": {
    "inputs": {
      "text": "best high quality\n(cat:1.2) sitting on a log in a forest\ncat has (long:0.9) (black:1.3) fur",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode"
  },
  "7": {
    "inputs": {
      "text": "(out of frame)\nblack and white\nbad eyes",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode"
  },
  "8": {
    "inputs": {
      "samples": [
        "3",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEDecode"
  },
  "9": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "8",
        0
      ]
    },
    "class_type": "SaveImage"
  },
  "10": {
    "inputs": {
      "image": "Untitled-1 (1).png",
      "choose file to upload": "image"
    },
    "class_type": "LoadImage",
    "is_changed": "677f93c5b52bd8fa7184ea65546bdf4b39af8252f40c9242f3cb02efe5fde6c9"
  },
  "12": {
    "inputs": {
      "pixels": [
        "10",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEEncode"
  },
  "14": {
    "inputs": {
      "width": 512,
      "height": 512,
      "batch_size": 20
    },
    "class_type": "EmptyLatentImage"
  }
}
```

**Comment by RupertAvery** [comment]
Implemented, closing for now

**Comment by jaythespacehound** [comment]
Apologies for the slow reply, here are three more images generated much the same way, I think there is always a KSampler node.
The difficulty might be with the various loaders. The checkpoint loader has two variants for example the 'normal one' (used above).
And the 'simple' one (used here).
![ComfyUI_21945_](https://user-images.githubusercontent.com/3013142/233700581-81f34f58-7b19-4fea-bad2-5a80e5cf0688.png)
![ComfyUI_21946_](https://user-images.githubusercontent.com/3013142/233700584-f924173e-ee11-4219-b9d2-35cb6c83897a.png)
![ComfyUI_21949_](https://user-images.githubusercontent.com/3013142/233700587-845f0952-f32e-4a6a-8dd2-5282f7ef481a.png)
but it always seems to have a:
"ckpt_name" which is the model being loaded which might be nice to include.

Here is an example using a LORA which also seems to parse ok for now (but it might be nice to include the lora name if one is used)
![ComfyUI_21950_](https://user-images.githubusercontent.com/3013142/233702250-95f673f5-df30-496f-88ee-abfea933238f.png)

Finally here is an img2img which v1.0 of DiffusionToolkit seems to not find at all?
![ComfyUI_21952_](https://user-images.githubusercontent.com/3013142/233703469-e164f2af-22b7-4cb8-a4e5-bd471288f625.png)

Thanks again for working on this! This is already a big help and most of the above are just quality of life improvements (I guess img2img is breaking)

**Comment by RupertAvery** [comment]
Thanks, I'll see what's happening witrh img2img

**Comment by RupertAvery** [comment]
latest v1.1 has fixed issues with your img2img sample, let me know if you have further issues. Thanks!
