### ISSUE TITLE
show all when no search term is entered

### ISSUE THREAD

**Issue by laurentopia** [RupertAvery/DiffusionToolkit#82]
like the finder and file explorer

**Comment by RupertAvery** [comment]
Do you mean, on startup?  I've added this in the latest code and will be available in the next release (with Sorting and Albums and Folders)

**Comment by laurentopia** [comment]
I mean when no text is entered in the field, which happens at startup but also when i delete the search field

**Comment by RupertAvery** [comment]
This is how it works currently. If you delete the search field and press enter, it will show all.

**Comment by laurentopia** [comment]
Ah that's not the default when the app launches and it requires enter which I'm not used to anymore.
