### ISSUE TITLE
Allow wildcards in Seed queries

### ISSUE THREAD

**Issue by laurentopia** [RupertAvery/DiffusionToolkit#83]
1. wildards like ? for single character and * for any number of characters, characters include space
2. /check:\*real\*, /seed:10348??45        etc... so we don't have to dig into the filter UI

**Comment by RupertAvery** [comment]
you can already query parameters using `seed: 1234567`. There are no wildcards for seed, as it is stored as a number, instead I opted to have a range e.g `seed: 1234567-1235000`

see:  https://github.com/RupertAvery/DiffusionToolkit/blob/master/Diffusion.Toolkit/Tips.md#advanced-searching

Wildcards in the prompt can be supported

**Comment by laurentopia** [comment]
wildcard on number is useful when you know that a seed had 355 in it but don't remember the rest nor how many digits, range can't handle such query
/check would search checkpoint name... so yeah rename that to whatever makes more sense.

**Comment by RupertAvery** [comment]
that would probably be `model:` then, as per A1111 metadata just to have some sort of reference.  There was another request to do model name searches in the search box so I will queue it in

Apparently numbers can be treated as strings in SQLite so I will add wildcard searches to seed.

Thanks!

**Comment by laurentopia** [comment]
Thanks to you!
