### ISSUE TITLE
remove the "scan complete found X new images" modal window

### ISSUE THREAD

**Issue by laurentopia** [RupertAvery/DiffusionToolkit#84]
gets in the way, can be a transient notification in the bottom corner

**Comment by RupertAvery** [comment]
This is already in progress

![image](https://user-images.githubusercontent.com/1910659/232933950-eb6aad99-c25a-445d-b6c8-108625d4c7bd.png)

The toast will go away after a few seconds, or when clicked

**Comment by laurentopia** [comment]
Great!
If the toast eats mouse clicks, better place it at the bottom.

**Comment by RupertAvery** [comment]
Yep, moved it to the bottom

**Comment by laurentopia** [comment]
That's great. Thanks.

**Comment by RupertAvery** [comment]
Implemented, closing
