### ISSUE TITLE
"Watch Folder" does not result in new images being found / Please remove new images found popup?

### ISSUE THREAD

**Issue by because-bot-fed** [RupertAvery/DiffusionToolkit#85]
Hello, 

First, I greatly appreciate this tool and that it's free, it's made flipping through newly generated stuff a much better experience than both the automatic1111 extension and file explorer. 

I've noticed one issue and one thing that would enhance my experience significantly if it's not too much trouble:

- Watch Folder doesn't seem to ever refresh my pictures, and I'm not sure why. I assume that's what the setting is intended to do. 
- The popup when scanning for new images has to be dismissed but I'd rather just not see it, or have the option to disable it. 

One other minor issue but I shift or control multi-select to drag into discord and a lot of times it doesn't quite "catch" and I'll just drag downward, which causes like a screen-edge-pan type of behavior. If this was more reliable / didn't require you to slowly and carefully drag that'd be huge.

Alternatively or maybe in addition or as a workaround, copying the actual files to the clipboard would work. Ctrl-C or context menu. 

Thanks for your efforts and taking the time to read!

**Comment by RupertAvery** [comment]
> a lot of times it doesn't quite "catch" and I'll just drag downward, which causes like a screen-edge-pan type of behavior. 

Perhaps you are dragging outside the white box (picture bounds) but still inside the blue box (selection bounds).  I'll try to see what's going on. The code is set to drag on item click, dunno why it doesn't hit test in the selection rectangle.

> The popup when scanning for new images has to be dismissed but I'd rather just not see it, or have the option to disable it.

A small "toast" on the lower right of the window is replacing the dialog, and dismisses itself after a few seconds, or on click.

![image](https://user-images.githubusercontent.com/1910659/232970874-3e17a815-9506-499d-bbe1-69eb1818da4e.png)

> Watch Folder doesn't seem to ever refresh my pictures, and I'm not sure why. I assume that's what the setting is intended to do.

I'm not sure what's going on either. It just stopped working for me early this year. Are you using A1111?

**Comment by because-bot-fed** [comment]
I am indeed using A1111 - and tyvm for the other updates! Greatly appreciated :) 

Regarding the click-drag: On my system there seems to just be some lag-time before it locks in what it's selected on.  You're right about the white/blue box behavior but even with the blue box if you were to do:

Click > Wait 50ms > Drag outside window 

It will do the drag/scroll thing.

If your cursor is in the window still after ~200ish ms? it will reselect/lock onto a new image. 

Fairly reproducible on my end. I'll attach a small videoclip that hopefully illustrates but feel free to let me know if you need more detail/testing. 


Unrelated but probably a very small ask, if not disregard since it's not super important - but it'd be nice if the opacity was able to be modified for the toggle that displays the prompt on top of the image. I love that I can toggle it but my prompts are ... large and slightly difficult to read against backgrounds that are lighter colors. 


Again tyvm for all your work and help on this, I'll check back later to see if there's anything else I can help test or answer! :)

**Comment by RupertAvery** [comment]
>  but it'd be nice if the opacity was able to be modified for the toggle that displays the prompt on top of the image

Are you using a light theme? Can you show your problem so I can think of some way to adjust for it?

**Comment by because-bot-fed** [comment]
Ah ok well I guess I didn't need the video that I forgot to attach! Thanks for the insight on that XD it's livable just gotta muscle memory not dragging too aggressively lol. 

Regarding the opacity, I'm on dark mode but it looks the same in both modes:
![Diffusion Toolkit_3Csk4usIXP](https://user-images.githubusercontent.com/20569547/233100682-00c0bc66-61f4-4ebc-8009-a0228bba060f.png)
![Diffusion Toolkit_RlxpD8WFwj](https://user-images.githubusercontent.com/20569547/233100694-9f59859f-f8df-4de8-bbc9-dcb65a8bb841.png)

The prompt text preview is just really hard to see against lighter backgrounds, it's not super important but if it's easily changed that'd be neat! :D

**Comment by RupertAvery** [comment]
CTRL-C has been added and background opactiy has been adjusted. Please take a look at the latest release.

**Comment by because-bot-fed** [comment]
Thanks much for all your work on this! :) The text is much much clearer now greatly appreciated.
