### ISSUE TITLE
Request: Turn the scan of subfolders into an optional setting

### ISSUE THREAD

**Issue by Trevor-Z** [RupertAvery/DiffusionToolkit#88]
Sometimes we might want to scan a folder for images with prompts embedded, but not its subfolders, so it would be useful to have this option available.

**Comment by RupertAvery** [comment]
I'll add a "Recursive" setting under Diffustion Folders setting. This will affect all folders.

**Comment by RupertAvery** [comment]
Available in v1.1, so will close this issue, thanks!
