### ISSUE TITLE
request: remove or hide the "albums" panel

### ISSUE THREAD

**Issue by Dahvikiin** [RupertAvery/DiffusionToolkit#89]
I checked the `changelog.md`, `tips.md`, and the `settings` and I did not find the option to remove or hide a panel that the user might not need and will not use or want to use.
My request is if it is possible to add an option to hide/remove this feature. thanks.

**Comment by RupertAvery** [comment]
Ok, I'll add an option View > Show / Hide Albums Pane

**Comment by RupertAvery** [comment]
This should already be in v1.1, so I will close this issue
