### ISSUE TITLE
Deleting associated text files

### ISSUE THREAD

**Issue by Neuralsplyce** [RupertAvery/DiffusionToolkit#9]
I have A1111 create a text file with the generation info for each image. I noticed when I delete images in DiffusionToolkit that the text files remain behind. The Image Browser extension to A1111 deletes the associated text files so there may be something in their code you can borrow (it may be as easy as specifying <filename.*> )

**Comment by RupertAvery** [comment]
Yeah, I don't normally use text files so I forget to account for them. I'll put it in the next update. Thanks!
