### ISSUE TITLE
Albums not working

### ISSUE THREAD

**Issue by R3dPhil** [RupertAvery/DiffusionToolkit#94]
When i create an Album it puts all images in the album and i can remove any pics from the album (if i do it doesnt work). What am I doing wrong?

**Comment by RupertAvery** [comment]
Can you describe how you create an album and use it?

**Comment by R3dPhil** [comment]
on the left panel click album - type in name - tade - but i cant add any images or remove any - i can only delete the album again (and i still have all my images which were it init, which is good in my opinion)

**Comment by R3dPhil** [comment]
now it works

**Comment by RupertAvery** [comment]
As mentioned in the instructions (F1) and https://github.com/RupertAvery/DiffusionToolkit/blob/master/Diffusion.Toolkit/Tips.md#albums

You can create an album by selecting some files, right click > Add to Album > New album.  You can add to an existing album the same way, the albums will appear under "New album"

You can also drag images onto the album to add them.
