### ISSUE TITLE
Bug: v1.1 unable to manual select prompt info. WildCards prompt

### ISSUE THREAD

**Issue by devilkkw** [RupertAvery/DiffusionToolkit#96]
In v1.0 i was able to manually select and copy prompt or part of it.
In v1.1 this is impossible, only way is copy full prompt by "copy" icon.
Also after generation parameter, we have more extra data for Wildcards prompt, but the copy icon not exist for it.

**Comment by RupertAvery** [comment]
> In v1.1 this is impossible, only way is copy full prompt by "copy" icon.

Sorry about this, a bug crept in that I had a hard time finding.  It seems to be style related, which can be a real headache to fix, but I'll get on it right away.

> Also after generation parameter, we have more extra data for Wildcards prompt, but the copy icon not exist for it.

Can you clarify this?
