### ISSUE TITLE
Deletion Fails Silently [v1.1]

### ISSUE THREAD

**Issue by splineclaw** [RupertAvery/DiffusionToolkit#98]
I have 40 items in my Recycle Bin, but when I run Edit > Empty Recycle Bin, nothing happens. 
The images are still there, both on disk and in Diffusion Toolkit. No log entries are made.

I went back from version 1.1 to version 1.0, and the deletion succeeded.
Upon returning to version 1.1 and trying to delete something, the problem persists.

**Comment by RupertAvery** [comment]
I am unable to replicate the issue.

When you click Edit > Empty Recycle Bin, do you get this warning?

![image](https://user-images.githubusercontent.com/1910659/235049834-80a8b350-01ae-4c68-be8d-1d2c13174575.png)

**Comment by splineclaw** [comment]
Yes, I get the warning.
If it makes any difference, I have used versions 0.9, 1.0, and 1.1 with this database previously.

**Comment by splineclaw** [comment]
The problem appears to be intermittent. I just successfully cleared recycle bin in 1.1. I then added something else and tried to delete it, but failed. I'm not sure why it worked that time after failing so many other times.
I also tried seeing if it made a difference whether items were added to the recycle bin in 1.0 or 1.1 - it makes no difference, 1.1 fails to delete in either case.

**Comment by RupertAvery** [comment]
Did you cancel after a Rebuild Metadata, and then empty recycle bin?

I have a bug where the cancellation token gets reused between operations.  Cancelling one thing then running empty recycle bin will result in the latter being cancelled automatically. Unfortunately I don't pop a message when you cancel, so it appears if nothing happened.

Thanks for leading me to find that.

That's the only reason it would work as you described with the current setup, and would make sense as I did move around some code related to the cancellation token recently, but I did nothing else with the empty recycle bin code.

If it still happens that way (empty recycle bin does nothing) after restarting the application, then emptying being the first thing you do, then I have more investigation cut out for me.

**Comment by splineclaw** [comment]
I was able to get the behavior (recycle bin does nothing) immediately after restarting, but not consistently.

First I opened the application, and emptied recycle bin - it succeeded.
I trashed an item and emptied recycle bin - it succeeded.
I trashed an item, closed the application, opened it again, trashed another item, and tried to empty recycle bin - it failed.
I closed the application, opened it up again, and tried to empty the recycle bin - it failed.

¯\_(ツ)_/¯

**Comment by splineclaw** [comment]
I have never used Rebuild Metadata on v1.1, though I can't remember whether I've canceled it before that.

**Comment by RupertAvery** [comment]
This is really strange. I can't replicate the issue nor see anything obvious that would cause intermittent issues like this.

This adds a fix to the cancellation token issue not being reset, but I don't know if it fixes your problem.

[v1.2b.zip](https://github.com/RupertAvery/DiffusionToolkit/files/11360478/v1.2b.zip)

Let me know how it goes.

**Comment by splineclaw** [comment]
Seems to fix the problem!
